import assert from "node:assert/strict"
import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { isoCountryCodeSet } from "./iso-country-codes"

interface FlagEntry {
	id: string
	name: string
	file: string
	circleViewBox?: string
	codes: string[]
}

interface FlagManifest {
	flags: FlagEntry[]
}

const idToken = "__RADIAN_FLAG_ID__"
const packageDirectory = path.resolve(
	path.dirname(fileURLToPath(import.meta.url)),
	".."
)
const manifestPath = path.join(packageDirectory, "source", "manifest.json")
const flagsDirectory = path.join(packageDirectory, "source", "flags")
const generatedDirectory = path.join(packageDirectory, "src", "generated")
const generatedPath = path.join(generatedDirectory, "flag-data.ts")

function escapeRegularExpression(value: string) {
	return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function getSvgContents(svg: string, file: string) {
	const match = svg.match(/^<svg\b[^>]*>([\s\S]*)<\/svg>\s*$/)
	assert.ok(match, `${file} must contain one root SVG element`)

	let contents = match[1].trim()
	const ids = Array.from(
		contents.matchAll(/\bid=(["'])([^"']+)\1/g),
		(result) => result[2]
	)

	contents = contents.replace(
		/\bid=(["'])([^"']+)\1/g,
		(_match, quote: string, id: string) => `id=${quote}${idToken}${id}${quote}`
	)

	for (const id of ids) {
		const escapedId = escapeRegularExpression(id)
		contents = contents
			.replace(
				new RegExp(`url\\(#${escapedId}\\)`, "g"),
				`url(#${idToken}${id})`
			)
			.replace(
				new RegExp(`(["'])#${escapedId}\\1`, "g"),
				(_match, quote: string) => `${quote}#${idToken}${id}${quote}`
			)
	}

	return contents
}

const manifest = JSON.parse(
	await readFile(manifestPath, "utf8")
) as FlagManifest
const flags: Record<
	string,
	{ name: string; svg: string; circleViewBox?: string }
> = {}
const codeToFlagId: Record<string, string> = {}
const publicFlagIds = new Set(["placeholder"])

for (const flag of manifest.flags) {
	for (const code of flag.codes) {
		if (!isoCountryCodeSet.has(code)) continue

		assert.ok(!codeToFlagId[code], `Duplicate country code: ${code}`)
		codeToFlagId[code] = flag.id
		publicFlagIds.add(flag.id)
	}
}

for (const flag of manifest.flags) {
	if (!publicFlagIds.has(flag.id)) continue

	const svg = await readFile(path.join(flagsDirectory, flag.file), "utf8")
	flags[flag.id] = {
		name: flag.name,
		svg: getSvgContents(svg, flag.file),
		...(flag.circleViewBox ? { circleViewBox: flag.circleViewBox } : {}),
	}
}

const flagIds = Object.keys(flags)
const source = `// This file is generated by scripts/generate.ts. Do not edit it directly.

export const idToken = ${JSON.stringify(idToken)}

export const flagIds = ${JSON.stringify(flagIds, null, "\t")} as const

export type FlagId = (typeof flagIds)[number]

interface GeneratedFlag {
\tname: string
\tsvg: string
\tcircleViewBox?: string
}

export const flagsById: Record<FlagId, GeneratedFlag> = ${JSON.stringify(flags, null, "\t")}

export const countryCodeToFlagId = ${JSON.stringify(codeToFlagId, null, "\t")} as const

export type CountryCode = keyof typeof countryCodeToFlagId

export const countryCodes = Object.freeze(
\tObject.keys(countryCodeToFlagId) as CountryCode[]
)
`

await mkdir(generatedDirectory, { recursive: true })
await writeFile(generatedPath, source)

console.log(
	`Generated ${Object.keys(flags).length - 1} flags for ${Object.keys(codeToFlagId).length} ISO country codes.`
)
