export const HOMEPAGE_COMPONENTS_LIST = [
	{
		title: "Button",
		description: "12 Components",
		url: "/docs/components/button",
		thumbnail: "/thumbnails/button.svg",
		thumbnailDark: `/thumbnails/button-dark.svg`,
		alt: "Button UI component illustration",
	},
	{
		title: "Input",
		description: "15 Components",
		url: "/docs/components/input",
		thumbnail: "/thumbnails/input.svg",
		thumbnailDark: `/thumbnails/input-dark.svg`,
		alt: "Input UI component illustration",
	},
	{
		title: "Check Box",
		description: "2 Components",
		url: "/docs/components/checkbox",
		thumbnail: "/thumbnails/checkbox.svg",
		thumbnailDark: `/thumbnails/checkbox-dark.svg`,
		alt: "Check Box UI component illustration",
	},

	{
		title: "Dialog",
		description: "2 Components",
		url: "/docs/components/dialog",
		thumbnail: "/thumbnails/dialog.svg",
		thumbnailDark: `/thumbnails/dialog-dark.svg`,
		alt: "Dialog UI component illustration",
	},
	{
		title: "Dropdown",
		description: "7 Components",
		url: "/docs/components/dropdown",
		thumbnail: "/thumbnails/dropdown.svg",
		thumbnailDark: `/thumbnails/dropdown-dark.svg`,
		alt: "Dropdown UI component illustration",
	},
	{
		title: "Sonner",
		description: "8 Components",
		url: "/docs/components/sonner",
		thumbnail: "/thumbnails/sonner.svg",
		thumbnailDark: `/thumbnails/sonner-dark.svg`,
		alt: "Toast UI component illustration",
	},
	{
		title: "Tabs",
		description: "3 Components",
		url: "/docs/components/tabs",
		thumbnail: "/thumbnails/tabs.svg",
		thumbnailDark: `/thumbnails/tabs-dark.svg`,
		alt: "Tabs UI component illustration",
	},
	{
		title: "Table",
		description: "2 Components",
		url: "/docs/components/table",
		thumbnail: "/thumbnails/table.svg",
		thumbnailDark: `/thumbnails/table-dark.svg`,
		alt: "Table UI component illustration",
	},
]
