export type NavigationItem = {
	title: string
	description?: string
	url: string
	thumbnail?: string
	thumbnailDark?: string
	alt?: string
}

export type NavigationSection = {
	title: string
	description?: string
	items: NavigationItem[]
}

export const navigationItems: NavigationSection[] = [
	{
		title: "Getting Started",
		items: [
			{ url: "/documentation/introduction", title: "Introduction" },
			{ url: "/documentation/installation", title: "Installation" },
			{ url: "/documentation/cli", title: "CLI" },
			{ url: "/documentation/figma", title: "Figma" },
			{ url: "/documentation/changelog", title: "Changelog" },
		],
	},
	{
		title: "Installation",
		items: [
			{ url: "/documentation/installation/next", title: "Nextjs" },
			{ url: "/documentation/installation/vite", title: "Vite" },
			{ url: "/documentation/installation/laravel", title: "Laravel" },
			{ url: "/documentation/installation/manual", title: "Manual" },
		],
	},
	{
		title: "Fundamentals",
		description: "Universal settings for building a strong foundation for a digital product",
		items: [
			{
				title: "Color styles",
				description: "156 colors, 70 color tokens",
				thumbnail: "/landing-svg/color-styles.svg",
				thumbnailDark: "/landing-svg/color-styles-dark.svg",
				url: "/documentation/colors",
				alt: "Palette of color styles illustration",
			},
			{
				title: "Typography",
				description: "17 Styles",
				url: "/documentation/typography",
				thumbnail: "/landing-svg/typography.svg",
				thumbnailDark: "/landing-svg/typography-dark.svg",
				alt: "Typography text styles illustration",
			},
			{
				title: "Icons",
				description: "1,200 Components",
				url: "/documentation/iconography",
				thumbnail: "/landing-svg/icons.svg",
				thumbnailDark: "/landing-svg/icons-dark.svg",
				alt: "Collection of icons illustration",
			},
			{
				title: "Corner Radius",
				description: "7 styles",
				thumbnail: "/landing-svg/corner-radius.svg",
				thumbnailDark: "/landing-svg/corner-radius-dark.svg",
				url: "#",
				alt: "Corner radius shapes illustration",
			},
			{
				title: "Grids",
				description: "8 Types",
				thumbnail: "/landing-svg/grids.svg",
				thumbnailDark: "/landing-svg/grids-dark.svg",
				url: "#",
				alt: "Grid layout illustration",
			},
			{
				title: "Elevation Levels",
				description: "16 styles",
				thumbnail: "/landing-svg/elevation-levels.svg",
				thumbnailDark: "/landing-svg/elevation-levels-dark.svg",
				url: "#",
				alt: "Elevation levels shadow illustration",
			},
			{
				title: "Spacing",
				description: "62 Values",
				thumbnail: "/landing-svg/spacing.svg",
				thumbnailDark: "/landing-svg/spacing-dark.svg",
				url: "#",
				alt: "Spacing and margin illustration",
			},
			{
				title: "Color / Theme",
				description: "8 Types",
				thumbnail: "/landing-svg/color-theme.svg",
				thumbnailDark: "/landing-svg/color-theme-dark.svg",
				url: "/documentation/default-theme",
				alt: "Color theme swatches illustration",
			},
			{
				title: "Logo",
				description: "--",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: "/landing-svg/coming-soon-dark.svg",
				url: "#",
				alt: "Coming soon placeholder illustration",
			},
		],
	},
	{
		title: "Components",
		items: [
			{
				title: "Alert",
				description: "12 Components",
				url: "/documentation/components/alert",
				thumbnail: "/landing-svg/alert.svg",
				thumbnailDark: `/landing-svg/alert-dark.svg`,
				alt: "Alert UI component illustration",
			},
			{
				title: "Accordion",
				description: "3 Components",
				url: "/documentation/components/accordion",
				thumbnail: "/landing-svg/accordion.svg",
				thumbnailDark: `/landing-svg/accordion-dark.svg`,
				alt: "Accordion UI component illustration",
			},
			{
				title: "Avatar",
				description: "4 Components",
				url: "/documentation/components/avatar",
				thumbnail: "/landing-svg/avatar.svg",
				thumbnailDark: `/landing-svg/avatar-dark.svg`,
				alt: "Avatar UI component illustration",
			},
			{
				title: "Badge",
				description: "2 Components",
				url: "/documentation/components/badge",
				thumbnail: "/landing-svg/badge.svg",
				thumbnailDark: `/landing-svg/badge-dark.svg`,
				alt: "Badge UI component illustration",
			},
			{
				title: "Banner",
				description: "11 Components",
				url: "/documentation/components/banner",
				thumbnail: "/landing-svg/banner.svg",
				thumbnailDark: `/landing-svg/banner-dark.svg`,
				alt: "Banner UI component illustration",
			},
			{
				title: "Breadcrumb",
				description: "5 Components",
				url: "/documentation/components/breadcrumb",
				thumbnail: "/landing-svg/breadcrumb.svg",
				thumbnailDark: `/landing-svg/breadcrumb-dark.svg`,
				alt: "Breadcrumb UI component illustration",
			},
			{
				title: "Button",
				description: "12 Components",
				url: "/documentation/components/buttons",
				thumbnail: "/landing-svg/button.svg",
				thumbnailDark: `/landing-svg/button-dark.svg`,
				alt: "Button UI component illustration",
			},
			{
				title: "Calendar",
				description: "4 Components",
				url: "/documentation/components/calendar",
				thumbnail: "/landing-svg/calendar.svg",
				thumbnailDark: `/landing-svg/calendar-dark.svg`,
				alt: "Calendar UI component illustration",
			},
			{
				title: "Code Area",
				description: "1 Component",
				url: "/documentation/components/code-area",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Code Area UI component illustration",
			},
			{
				title: "Color Picker",
				description: "3 Components",
				url: "/documentation/components/color-picker",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Color Picker UI component illustration",
			},
			{
				title: "Currency Amount",
				description: "3 Components",
				url: "/documentation/components/currency-amount",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Currency Amount UI component illustration",
			},
			{
				title: "Check Box",
				description: "2 Components",
				url: "/documentation/components/checkbox",
				thumbnail: "/landing-svg/checkbox.svg",
				thumbnailDark: `/landing-svg/checkbox-dark.svg`,
				alt: "Check Box UI component illustration",
			},
			{
				title: "Date Picker",
				description: "1 Component",
				url: "/documentation/components/date-picker",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Date Picker UI component illustration",
			},
			{
				title: "Divider",
				description: "3 Components",
				url: "/documentation/components/divider",
				thumbnail: "/landing-svg/divider.svg",
				thumbnailDark: `/landing-svg/divider-dark.svg`,
				alt: "Divider UI component illustration",
			},
			{
				title: "Dropdown",
				description: "7 Components",
				url: "/documentation/components/dropdown",
				thumbnail: "/landing-svg/dropdown.svg",
				thumbnailDark: `/landing-svg/dropdown-dark.svg`,
				alt: "Dropdown UI component illustration",
			},
			{
				title: "Drawer",
				description: "2 Components",
				url: "/documentation/components/drawer",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Drawer UI component illustration",
			},
			{
				title: "Input",
				description: "15 Components",
				url: "/documentation/components/inputs",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Input UI component illustration",
			},
			{
				title: "Input OTP",
				description: "2 Components",
				url: "/documentation/components/input-otp",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Input OTP UI component illustration",
			},
			{
				title: "File Upload",
				description: "4 Components",
				url: "/documentation/components/file-upload",
				thumbnail: "/landing-svg/file-upload.svg",
				thumbnailDark: `/landing-svg/file-upload-dark.svg`,
				alt: "File Upload UI component illustration",
			},
			{
				title: "Form",
				description: "12 Components",
				url: "/documentation/components/forms",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Form UI component illustration",
			},
			{
				title: "Hover Card",
				description: "4 Components",
				url: "/documentation/components/hover-card",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Hover Card UI component illustration",
			},
			{
				title: "Modal",
				description: "2 Components",
				url: "/documentation/components/modal",
				thumbnail: "/landing-svg/modal.svg",
				thumbnailDark: `/landing-svg/modal-dark.svg`,
				alt: "Modal UI component illustration",
			},
			{
				title: "Pagination",
				description: "3 Components",
				url: "/documentation/components/pagination",
				thumbnail: "/landing-svg/pagination.svg",
				thumbnailDark: `/landing-svg/pagination-dark.svg`,
				alt: "Pagination UI component illustration",
			},
			{
				title: "Password",
				description: "2 Components",
				url: "/documentation/components/password",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Password UI component illustration",
			},
			{
				title: "Phone Number",
				description: "2 Components",
				url: "/documentation/components/phone-number",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Phone Number UI component illustration",
			},
			{
				title: "Popover",
				description: "3 Components",
				url: "/documentation/components/popover",
				thumbnail: "/landing-svg/popover.svg",
				thumbnailDark: `/landing-svg/popover-dark.svg`,
				alt: "Popover UI component illustration",
			},
			{
				title: "Progress Bar",
				description: "1 Component",
				url: "/documentation/components/progress-bar",
				thumbnail: "/landing-svg/progress-bar.svg",
				thumbnailDark: `/landing-svg/progress-bar-dark.svg`,
				alt: "Progress Bar UI component illustration",
			},
			{
				title: "Radio Group",
				description: "4 Components",
				url: "/documentation/components/radio-group",
				thumbnail: "/landing-svg/radio-buttons.svg",
				thumbnailDark: `/landing-svg/radio-buttons-dark.svg`,
				alt: "Radio Group UI component illustration",
			},
			{
				title: "Resizable",
				description: "2 Components",
				url: "/documentation/components/resizable",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Resizable UI component illustration",
			},
			{
				title: "Search",
				description: "1 Component",
				url: "/documentation/components/search",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Search UI component illustration",
			},
			{
				title: "Select",
				description: "6 Components",
				url: "/documentation/components/select",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Select UI component illustration",
			},
			{
				title: "Skeleton",
				description: "2 Components",
				url: "/documentation/components/skeleton",
				thumbnail: "/landing-svg/skeleton.svg",
				thumbnailDark: `/landing-svg/skeleton-dark.svg`,
				alt: "Skeleton UI component illustration",
			},
			{
				title: "Slider",
				description: "3 Components",
				url: "/documentation/components/slider",
				thumbnail: "/landing-svg/slider.svg",
				thumbnailDark: `/landing-svg/slider-dark.svg`,
				alt: "Slider UI component illustration",
			},
			{
				title: "Spinner",
				description: "5 Components",
				url: "/documentation/components/spinner",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Spinner UI component illustration",
			},
			{
				title: "Switch",
				description: "4 Components",
				url: "/documentation/components/switch",
				thumbnail: "/landing-svg/switch.svg",
				thumbnailDark: `/landing-svg/switch-dark.svg`,
				alt: "Switch UI component illustration",
			},
			{
				title: "Table",
				description: "2 Components",
				url: "/documentation/components/table",
				thumbnail: "/landing-svg/table.svg",
				thumbnailDark: `/landing-svg/table-dark.svg`,
				alt: "Table UI component illustration",
			},
			{
				title: "Tabs",
				description: "3 Components",
				url: "/documentation/components/tabs",
				thumbnail: "/landing-svg/tabs.svg",
				thumbnailDark: `/landing-svg/tabs-dark.svg`,
				alt: "Tabs UI component illustration",
			},
			{
				title: "Text Area",
				description: "1 Component",
				url: "/documentation/components/text-area",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Text Area UI component illustration",
			},
			{
				title: "Time Picker",
				description: "2 Components",
				url: "/documentation/components/time-picker",
				thumbnail: "/landing-svg/coming-soon.svg",
				thumbnailDark: `/landing-svg/coming-soon-dark.svg`,
				alt: "Time Picker UI component illustration",
			},
			{
				title: "Toast",
				description: "8 Components",
				url: "/documentation/components/toast",
				thumbnail: "/landing-svg/sonner.svg",
				thumbnailDark: `/landing-svg/sonner-dark.svg`,
				alt: "Toast UI component illustration",
			},
			{
				title: "Tooltip",
				description: "3 Components",
				url: "/documentation/components/tooltip",
				thumbnail: "/landing-svg/tooltip.svg",
				thumbnailDark: `/landing-svg/tooltip-dark.svg`,
				alt: "Tooltip UI component illustration",
			},
		].sort((a, b) => a.title.localeCompare(b.title)),
	},
	{
		title: "Animations",
		items: [
			{ url: "/documentation/animations/typing-text", title: "Typing Text" },
			{
				url: "/documentation/animations/gradient-text",
				title: "Gradient Text",
			},
			{
				url: "/documentation/animations/draggable",
				title: "Draggable",
			},
			{
				url: "/documentation/animations/fade",
				title: "Fade",
			},
			{
				url: "/documentation/animations/infinite-scroll",
				title: "Infinite Scroll",
			},
			{
				url: "/documentation/animations/pointer",
				title: "Pointer",
			},
			{
				url: "/documentation/animations/border-beam",
				title: "Border Beam",
			},
			{
				url: "/documentation/animations/changing-text",
				title: "Changing Text",
			},
			{
				url: "/documentation/animations/animated-list",
				title: "Animated List",
			},
			{
				url: "/documentation/animations/text-reveal",
				title: "Text Reveal",
			},
		].sort((a, b) => a.title.localeCompare(b.title)),
	},
]
