export type NavigationItem = {
	title: string
	description?: string
	url: string
	thumbnail?: string
	thumbnailDark?: string
	alt?: string
}

export type NavigationSection = {
	title: string
	description?: string
	items: NavigationItem[]
	searchIcon?: string
}

export const navigationItems: NavigationSection[] = [
	{
		title: "Getting Started",
		searchIcon: "/search-icons/search-installation.svg",
		items: [
			{ url: "/docs/getting-started/introduction", title: "Introduction" },
			{ url: "/docs/getting-started/installation", title: "Installation" },
			{ url: "/docs/getting-started/cli", title: "CLI" },
			{ url: "/docs/getting-started/figma", title: "Figma" },
			{ url: "/docs/getting-started/changelog", title: "Changelog" },
		],
	},
	{
		title: "Installation",
		searchIcon: "/search-icons/search-installation.svg",
		items: [
			{ url: "/docs/installation/next", title: "Nextjs" },
			{ url: "/docs/installation/vite", title: "Vite" },
			{ url: "/docs/installation/manual", title: "Manual" },
		],
	},
	{
		title: "Fundamentals",
		searchIcon: "/search-icons/search-fundamentals.svg",
		description: "Universal settings for building a strong foundation for a digital product",
		items: [
			{
				title: "Color styles",
				description: "156 colors, 70 color tokens",
				thumbnail: "/thumbnails/color-styles.webp",
				thumbnailDark: "/thumbnails/color-styles-dark.webp",
				url: "/docs/fundamentals/colors",
				alt: "Palette of color styles illustration",
			},
			{
				title: "Typography",
				description: "17 Styles",
				url: "/docs/fundamentals/typography",
				thumbnail: "/thumbnails/typography.webp",
				thumbnailDark: "/thumbnails/typography-dark.webp",
				alt: "Typography text styles illustration",
			},
			{
				title: "Icons",
				description: "1,200 Components",
				url: "/docs/fundamentals/iconography",
				thumbnail: "/thumbnails/icons.webp",
				thumbnailDark: "/thumbnails/icons-dark.webp",
				alt: "Collection of icons illustration",
			},
			{
				title: "Theme",
				description: "8 Types",
				thumbnail: "/thumbnails/color-theme.webp",
				thumbnailDark: "/thumbnails/color-theme-dark.webp",
				url: "/docs/fundamentals/theme",
				alt: "Color theme swatches illustration",
			},
		],
	},
	{
		title: "Components",
		searchIcon: "/search-icons/search-components.svg",
		items: [
			{
				title: "Alert",
				description: "12 Components",
				url: "/docs/components/alert",
				thumbnail: "/thumbnails/alert.webp",
				thumbnailDark: `/thumbnails/alert-dark.webp`,
				alt: "Alert UI component illustration",
			},
			{
				title: "Alert Dialog",
				description: "1 Component",
				url: "/docs/components/alert-dialog",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Alert Dialog UI component illustration",
			},
			{
				title: "Accordion",
				description: "3 Components",
				url: "/docs/components/accordion",
				thumbnail: "/thumbnails/accordion.webp",
				thumbnailDark: `/thumbnails/accordion-dark.webp`,
				alt: "Accordion UI component illustration",
			},
			{
				title: "Avatar",
				description: "4 Components",
				url: "/docs/components/avatar",
				thumbnail: "/thumbnails/avatar.webp",
				thumbnailDark: `/thumbnails/avatar-dark.webp`,
				alt: "Avatar UI component illustration",
			},
			{
				title: "Badge",
				description: "2 Components",
				url: "/docs/components/badge",
				thumbnail: "/thumbnails/badge.webp",
				thumbnailDark: `/thumbnails/badge-dark.webp`,
				alt: "Badge UI component illustration",
			},
			{
				title: "Banner",
				description: "11 Components",
				url: "/docs/components/banner",
				thumbnail: "/thumbnails/banner.webp",
				thumbnailDark: `/thumbnails/banner-dark.webp`,
				alt: "Banner UI component illustration",
			},
			{
				title: "Breadcrumb",
				description: "5 Components",
				url: "/docs/components/breadcrumb",
				thumbnail: "/thumbnails/breadcrumb.webp",
				thumbnailDark: `/thumbnails/breadcrumb-dark.webp`,
				alt: "Breadcrumb UI component illustration",
			},
			{
				title: "Button",
				description: "12 Components",
				url: "/docs/components/button",
				thumbnail: "/thumbnails/button.webp",
				thumbnailDark: `/thumbnails/button-dark.webp`,
				alt: "Button UI component illustration",
			},
			{
				title: "Calendar",
				description: "4 Components",
				url: "/docs/components/calendar",
				thumbnail: "/thumbnails/calendar.webp",
				thumbnailDark: `/thumbnails/calendar-dark.webp`,
				alt: "Calendar UI component illustration",
			},
			{
				title: "Code Area",
				description: "1 Component",
				url: "/docs/components/code-area",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Code Area UI component illustration",
			},
			{
				title: "Collapsible",
				description: "1 Component",
				url: "/docs/components/collapsible",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Collapsible UI component illustration",
			},
			{
				title: "Currency Amount",
				description: "3 Components",
				url: "/docs/components/currency-amount",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Currency Amount UI component illustration",
			},
			{
				title: "Check Box",
				description: "2 Components",
				url: "/docs/components/checkbox",
				thumbnail: "/thumbnails/checkbox.webp",
				thumbnailDark: `/thumbnails/checkbox-dark.webp`,
				alt: "Check Box UI component illustration",
			},
			{
				title: "Date Picker",
				description: "1 Component",
				url: "/docs/components/date-picker",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Date Picker UI component illustration",
			},
			{
				title: "Dialog",
				description: "2 Components",
				url: "/docs/components/dialog",
				thumbnail: "/thumbnails/modal.webp",
				thumbnailDark: `/thumbnails/modal-dark.webp`,
				alt: "Dialog UI component illustration",
			},
			{
				title: "Divider",
				description: "3 Components",
				url: "/docs/components/divider",
				thumbnail: "/thumbnails/divider.webp",
				thumbnailDark: `/thumbnails/divider-dark.webp`,
				alt: "Divider UI component illustration",
			},
			{
				title: "Dropdown",
				description: "7 Components",
				url: "/docs/components/dropdown",
				thumbnail: "/thumbnails/dropdown.webp",
				thumbnailDark: `/thumbnails/dropdown-dark.webp`,
				alt: "Dropdown UI component illustration",
			},
			{
				title: "Drawer",
				description: "2 Components",
				url: "/docs/components/drawer",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Drawer UI component illustration",
			},
			{
				title: "Input",
				description: "15 Components",
				url: "/docs/components/input",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Input UI component illustration",
			},
			{
				title: "One Time Password Field",
				description: "2 Components",
				url: "/docs/components/one-time-password-field",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "One Time Password Field UI component illustration",
			},
			{
				title: "File Upload",
				description: "4 Components",
				url: "/docs/components/file-upload",
				thumbnail: "/thumbnails/file-upload.webp",
				thumbnailDark: `/thumbnails/file-upload-dark.webp`,
				alt: "File Upload UI component illustration",
			},
			{
				title: "Form",
				description: "12 Components",
				url: "/docs/components/form",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Form UI component illustration",
			},
			{
				title: "Hover Card",
				description: "4 Components",
				url: "/docs/components/hover-card",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Hover Card UI component illustration",
			},
			{
				title: "Label",
				description: "Label text",
				url: "/docs/components/label",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Label text",
			},

			{
				title: "Pagination",
				description: "3 Components",
				url: "/docs/components/pagination",
				thumbnail: "/thumbnails/pagination.webp",
				thumbnailDark: `/thumbnails/pagination-dark.webp`,
				alt: "Pagination UI component illustration",
			},
			{
				title: "Password",
				description: "2 Components",
				url: "/docs/components/password",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Password UI component illustration",
			},
			{
				title: "Phone Number",
				description: "2 Components",
				url: "/docs/components/phone-number",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Phone Number UI component illustration",
			},
			{
				title: "Popover",
				description: "3 Components",
				url: "/docs/components/popover",
				thumbnail: "/thumbnails/popover.webp",
				thumbnailDark: `/thumbnails/popover-dark.webp`,
				alt: "Popover UI component illustration",
			},
			{
				title: "Progress",
				description: "1 Component",
				url: "/docs/components/progress",
				thumbnail: "/thumbnails/progress-bar.webp",
				thumbnailDark: `/thumbnails/progress-bar-dark.webp`,
				alt: "Progress Bar UI component illustration",
			},
			{
				title: "Radio Group",
				description: "4 Components",
				url: "/docs/components/radio-group",
				thumbnail: "/thumbnails/radio-buttons.webp",
				thumbnailDark: `/thumbnails/radio-buttons-dark.webp`,
				alt: "Radio Group UI component illustration",
			},
			{
				title: "Resizable",
				description: "2 Components",
				url: "/docs/components/resizable",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Resizable UI component illustration",
			},
			{
				title: "Search",
				description: "1 Component",
				url: "/docs/components/search",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Search UI component illustration",
			},
			{
				title: "Select",
				description: "6 Components",
				url: "/docs/components/select",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Select UI component illustration",
			},
			{
				title: "Skeleton",
				description: "2 Components",
				url: "/docs/components/skeleton",
				thumbnail: "/thumbnails/skeleton.webp",
				thumbnailDark: `/thumbnails/skeleton-dark.webp`,
				alt: "Skeleton UI component illustration",
			},
			{
				title: "Slider",
				description: "3 Components",
				url: "/docs/components/slider",
				thumbnail: "/thumbnails/slider.webp",
				thumbnailDark: `/thumbnails/slider-dark.webp`,
				alt: "Slider UI component illustration",
			},
			{
				title: "Spinner",
				description: "5 Components",
				url: "/docs/components/spinner",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Spinner UI component illustration",
			},
			{
				title: "Switch",
				description: "4 Components",
				url: "/docs/components/switch",
				thumbnail: "/thumbnails/switch.webp",
				thumbnailDark: `/thumbnails/switch-dark.webp`,
				alt: "Switch UI component illustration",
			},
			{
				title: "Table",
				description: "2 Components",
				url: "/docs/components/table",
				thumbnail: "/thumbnails/table.webp",
				thumbnailDark: `/thumbnails/table-dark.webp`,
				alt: "Table UI component illustration",
			},
			{
				title: "Tabs",
				description: "3 Components",
				url: "/docs/components/tabs",
				thumbnail: "/thumbnails/tabs.webp",
				thumbnailDark: `/thumbnails/tabs-dark.webp`,
				alt: "Tabs UI component illustration",
			},
			{
				title: "Text Area",
				description: "1 Component",
				url: "/docs/components/text-area",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Text Area UI component illustration",
			},
			{
				title: "Toast",
				description: "8 Components",
				url: "/docs/components/toast",
				thumbnail: "/thumbnails/sonner.webp",
				thumbnailDark: `/thumbnails/sonner-dark.webp`,
				alt: "Toast UI component illustration",
			},
			{
				title: "Tooltip",
				description: "3 Components",
				url: "/docs/components/tooltip",
				thumbnail: "/thumbnails/tooltip.webp",
				thumbnailDark: `/thumbnails/tooltip-dark.webp`,
				alt: "Tooltip UI component illustration",
			},
		].sort((a, b) => a.title.localeCompare(b.title)),
	},
	{
		title: "Animations",
		searchIcon: "/search-icons/search-components.svg",
		items: [
			{ url: "/docs/animations/typing-text", title: "Typing Text" },
			{
				url: "/docs/animations/gradient-text",
				title: "Gradient Text",
			},
			{
				url: "/docs/animations/draggable",
				title: "Draggable",
			},
			{
				url: "/docs/animations/fade",
				title: "Fade",
			},
			{
				url: "/docs/animations/infinite-scroll",
				title: "Infinite Scroll",
			},
			{
				url: "/docs/animations/pointer",
				title: "Pointer",
			},
			{
				url: "/docs/animations/border-beam",
				title: "Border Beam",
			},
			{
				url: "/docs/animations/changing-text",
				title: "Changing Text",
			},
			{
				url: "/docs/animations/animated-list",
				title: "Animated List",
			},
			{
				url: "/docs/animations/text-reveal",
				title: "Text Reveal",
			},
		].sort((a, b) => a.title.localeCompare(b.title)),
	},
]
