export type NavigationItem = {
	title: string
	description?: string
	url: string
	thumbnail?: string
	thumbnailDark?: string
	alt?: string
}

export type NavigationSection = {
	title: string
	description?: string
	items: NavigationItem[]
}

export const navigationItems: NavigationSection[] = [
	{
		title: "Getting Started",
		items: [
			{ url: "/documentation/introduction", title: "Introduction" },
			{ url: "/documentation/installation", title: "Installation" },
			{ url: "/documentation/cli", title: "CLI" },
			{ url: "/documentation/figma", title: "Figma" },
			{ url: "/documentation/changelog", title: "Changelog" },
		],
	},
	{
		title: "Installation",
		items: [
			{ url: "/documentation/installation/next", title: "Nextjs" },
			{ url: "/documentation/installation/vite", title: "Vite" },
			{ url: "/documentation/installation/laravel", title: "Laravel" },
			{ url: "/documentation/installation/manual", title: "Manual" },
		],
	},
	{
		title: "Fundamentals",
		description: "Universal settings for building a strong foundation for a digital product",
		items: [
			{
				title: "Color styles",
				description: "156 colors, 70 color tokens",
				thumbnail: "/thumbnails/color-styles.webp",
				thumbnailDark: "/thumbnails/color-styles-dark.webp",
				url: "/documentation/colors",
				alt: "Palette of color styles illustration",
			},
			{
				title: "Typography",
				description: "17 Styles",
				url: "/documentation/typography",
				thumbnail: "/thumbnails/typography.webp",
				thumbnailDark: "/thumbnails/typography-dark.webp",
				alt: "Typography text styles illustration",
			},
			{
				title: "Icons",
				description: "1,200 Components",
				url: "/documentation/iconography",
				thumbnail: "/thumbnails/icons.webp",
				thumbnailDark: "/thumbnails/icons-dark.webp",
				alt: "Collection of icons illustration",
			},
			{
				title: "Corner Radius",
				description: "7 styles",
				thumbnail: "/thumbnails/corner-radius.webp",
				thumbnailDark: "/thumbnails/corner-radius-dark.webp",
				url: "#",
				alt: "Corner radius shapes illustration",
			},
			{
				title: "Grids",
				description: "8 Types",
				thumbnail: "/thumbnails/grids.webp",
				thumbnailDark: "/thumbnails/grids-dark.webp",
				url: "#",
				alt: "Grid layout illustration",
			},
			{
				title: "Elevation Levels",
				description: "16 styles",
				thumbnail: "/thumbnails/elevation-levels.webp",
				thumbnailDark: "/thumbnails/elevation-levels-dark.webp",
				url: "#",
				alt: "Elevation levels shadow illustration",
			},
			{
				title: "Spacing",
				description: "62 Values",
				thumbnail: "/thumbnails/spacing.webp",
				thumbnailDark: "/thumbnails/spacing-dark.webp",
				url: "#",
				alt: "Spacing and margin illustration",
			},
			{
				title: "Color / Theme",
				description: "8 Types",
				thumbnail: "/thumbnails/color-theme.webp",
				thumbnailDark: "/thumbnails/color-theme-dark.webp",
				url: "/documentation/default-theme",
				alt: "Color theme swatches illustration",
			},
			{
				title: "Logo",
				description: "--",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: "/thumbnails/coming-soon-dark.webp",
				url: "#",
				alt: "Coming soon placeholder illustration",
			},
		],
	},
	{
		title: "Components",
		items: [
			{
				title: "Alert",
				description: "12 Components",
				url: "/documentation/components/alert",
				thumbnail: "/thumbnails/alert.webp",
				thumbnailDark: `/thumbnails/alert-dark.webp`,
				alt: "Alert UI component illustration",
			},
			{
				title: "Accordion",
				description: "3 Components",
				url: "/documentation/components/accordion",
				thumbnail: "/thumbnails/accordion.webp",
				thumbnailDark: `/thumbnails/accordion-dark.webp`,
				alt: "Accordion UI component illustration",
			},
			{
				title: "Avatar",
				description: "4 Components",
				url: "/documentation/components/avatar",
				thumbnail: "/thumbnails/avatar.webp",
				thumbnailDark: `/thumbnails/avatar-dark.webp`,
				alt: "Avatar UI component illustration",
			},
			{
				title: "Badge",
				description: "2 Components",
				url: "/documentation/components/badge",
				thumbnail: "/thumbnails/badge.webp",
				thumbnailDark: `/thumbnails/badge-dark.webp`,
				alt: "Badge UI component illustration",
			},
			{
				title: "Banner",
				description: "11 Components",
				url: "/documentation/components/banner",
				thumbnail: "/thumbnails/banner.webp",
				thumbnailDark: `/thumbnails/banner-dark.webp`,
				alt: "Banner UI component illustration",
			},
			{
				title: "Breadcrumb",
				description: "5 Components",
				url: "/documentation/components/breadcrumb",
				thumbnail: "/thumbnails/breadcrumb.webp",
				thumbnailDark: `/thumbnails/breadcrumb-dark.webp`,
				alt: "Breadcrumb UI component illustration",
			},
			{
				title: "Button",
				description: "12 Components",
				url: "/documentation/components/buttons",
				thumbnail: "/thumbnails/button.webp",
				thumbnailDark: `/thumbnails/button-dark.webp`,
				alt: "Button UI component illustration",
			},
			{
				title: "Calendar",
				description: "4 Components",
				url: "/documentation/components/calendar",
				thumbnail: "/thumbnails/calendar.webp",
				thumbnailDark: `/thumbnails/calendar-dark.webp`,
				alt: "Calendar UI component illustration",
			},
			{
				title: "Code Area",
				description: "1 Component",
				url: "/documentation/components/code-area",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Code Area UI component illustration",
			},
			{
				title: "Color Picker",
				description: "3 Components",
				url: "/documentation/components/color-picker",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Color Picker UI component illustration",
			},
			{
				title: "Currency Amount",
				description: "3 Components",
				url: "/documentation/components/currency-amount",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Currency Amount UI component illustration",
			},
			{
				title: "Check Box",
				description: "2 Components",
				url: "/documentation/components/checkbox",
				thumbnail: "/thumbnails/checkbox.webp",
				thumbnailDark: `/thumbnails/checkbox-dark.webp`,
				alt: "Check Box UI component illustration",
			},
			{
				title: "Date Picker",
				description: "1 Component",
				url: "/documentation/components/date-picker",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Date Picker UI component illustration",
			},
			{
				title: "Divider",
				description: "3 Components",
				url: "/documentation/components/divider",
				thumbnail: "/thumbnails/divider.webp",
				thumbnailDark: `/thumbnails/divider-dark.webp`,
				alt: "Divider UI component illustration",
			},
			{
				title: "Dropdown",
				description: "7 Components",
				url: "/documentation/components/dropdown",
				thumbnail: "/thumbnails/dropdown.webp",
				thumbnailDark: `/thumbnails/dropdown-dark.webp`,
				alt: "Dropdown UI component illustration",
			},
			{
				title: "Drawer",
				description: "2 Components",
				url: "/documentation/components/drawer",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Drawer UI component illustration",
			},
			{
				title: "Input",
				description: "15 Components",
				url: "/documentation/components/inputs",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Input UI component illustration",
			},
			{
				title: "Input OTP",
				description: "2 Components",
				url: "/documentation/components/input-otp",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Input OTP UI component illustration",
			},
			{
				title: "File Upload",
				description: "4 Components",
				url: "/documentation/components/file-upload",
				thumbnail: "/thumbnails/file-upload.webp",
				thumbnailDark: `/thumbnails/file-upload-dark.webp`,
				alt: "File Upload UI component illustration",
			},
			{
				title: "Form",
				description: "12 Components",
				url: "/documentation/components/forms",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Form UI component illustration",
			},
			{
				title: "Hover Card",
				description: "4 Components",
				url: "/documentation/components/hover-card",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Hover Card UI component illustration",
			},
			{
				title: "Modal",
				description: "2 Components",
				url: "/documentation/components/modal",
				thumbnail: "/thumbnails/modal.webp",
				thumbnailDark: `/thumbnails/modal-dark.webp`,
				alt: "Modal UI component illustration",
			},
			{
				title: "Pagination",
				description: "3 Components",
				url: "/documentation/components/pagination",
				thumbnail: "/thumbnails/pagination.webp",
				thumbnailDark: `/thumbnails/pagination-dark.webp`,
				alt: "Pagination UI component illustration",
			},
			{
				title: "Password",
				description: "2 Components",
				url: "/documentation/components/password",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Password UI component illustration",
			},
			{
				title: "Phone Number",
				description: "2 Components",
				url: "/documentation/components/phone-number",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Phone Number UI component illustration",
			},
			{
				title: "Popover",
				description: "3 Components",
				url: "/documentation/components/popover",
				thumbnail: "/thumbnails/popover.webp",
				thumbnailDark: `/thumbnails/popover-dark.webp`,
				alt: "Popover UI component illustration",
			},
			{
				title: "Progress Bar",
				description: "1 Component",
				url: "/documentation/components/progress-bar",
				thumbnail: "/thumbnails/progress-bar.webp",
				thumbnailDark: `/thumbnails/progress-bar-dark.webp`,
				alt: "Progress Bar UI component illustration",
			},
			{
				title: "Radio Group",
				description: "4 Components",
				url: "/documentation/components/radio-group",
				thumbnail: "/thumbnails/radio-buttons.webp",
				thumbnailDark: `/thumbnails/radio-buttons-dark.webp`,
				alt: "Radio Group UI component illustration",
			},
			{
				title: "Resizable",
				description: "2 Components",
				url: "/documentation/components/resizable",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Resizable UI component illustration",
			},
			{
				title: "Search",
				description: "1 Component",
				url: "/documentation/components/search",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Search UI component illustration",
			},
			{
				title: "Select",
				description: "6 Components",
				url: "/documentation/components/select",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Select UI component illustration",
			},
			{
				title: "Skeleton",
				description: "2 Components",
				url: "/documentation/components/skeleton",
				thumbnail: "/thumbnails/skeleton.webp",
				thumbnailDark: `/thumbnails/skeleton-dark.webp`,
				alt: "Skeleton UI component illustration",
			},
			{
				title: "Slider",
				description: "3 Components",
				url: "/documentation/components/slider",
				thumbnail: "/thumbnails/slider.webp",
				thumbnailDark: `/thumbnails/slider-dark.webp`,
				alt: "Slider UI component illustration",
			},
			{
				title: "Spinner",
				description: "5 Components",
				url: "/documentation/components/spinner",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Spinner UI component illustration",
			},
			{
				title: "Switch",
				description: "4 Components",
				url: "/documentation/components/switch",
				thumbnail: "/thumbnails/switch.webp",
				thumbnailDark: `/thumbnails/switch-dark.webp`,
				alt: "Switch UI component illustration",
			},
			{
				title: "Table",
				description: "2 Components",
				url: "/documentation/components/table",
				thumbnail: "/thumbnails/table.webp",
				thumbnailDark: `/thumbnails/table-dark.webp`,
				alt: "Table UI component illustration",
			},
			{
				title: "Tabs",
				description: "3 Components",
				url: "/documentation/components/tabs",
				thumbnail: "/thumbnails/tabs.webp",
				thumbnailDark: `/thumbnails/tabs-dark.webp`,
				alt: "Tabs UI component illustration",
			},
			{
				title: "Text Area",
				description: "1 Component",
				url: "/documentation/components/text-area",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Text Area UI component illustration",
			},
			{
				title: "Time Picker",
				description: "2 Components",
				url: "/documentation/components/time-picker",
				thumbnail: "/thumbnails/coming-soon.webp",
				thumbnailDark: `/thumbnails/coming-soon-dark.webp`,
				alt: "Time Picker UI component illustration",
			},
			{
				title: "Toast",
				description: "8 Components",
				url: "/documentation/components/toast",
				thumbnail: "/thumbnails/sonner.webp",
				thumbnailDark: `/thumbnails/sonner-dark.webp`,
				alt: "Toast UI component illustration",
			},
			{
				title: "Tooltip",
				description: "3 Components",
				url: "/documentation/components/tooltip",
				thumbnail: "/thumbnails/tooltip.webp",
				thumbnailDark: `/thumbnails/tooltip-dark.webp`,
				alt: "Tooltip UI component illustration",
			},
		].sort((a, b) => a.title.localeCompare(b.title)),
	},
	{
		title: "Animations",
		items: [
			{ url: "/documentation/animations/typing-text", title: "Typing Text" },
			{
				url: "/documentation/animations/gradient-text",
				title: "Gradient Text",
			},
			{
				url: "/documentation/animations/draggable",
				title: "Draggable",
			},
			{
				url: "/documentation/animations/fade",
				title: "Fade",
			},
			{
				url: "/documentation/animations/infinite-scroll",
				title: "Infinite Scroll",
			},
			{
				url: "/documentation/animations/pointer",
				title: "Pointer",
			},
			{
				url: "/documentation/animations/border-beam",
				title: "Border Beam",
			},
			{
				url: "/documentation/animations/changing-text",
				title: "Changing Text",
			},
			{
				url: "/documentation/animations/animated-list",
				title: "Animated List",
			},
			{
				url: "/documentation/animations/text-reveal",
				title: "Text Reveal",
			},
		].sort((a, b) => a.title.localeCompare(b.title)),
	},
]
