export const websiteMetadata = {
	name: "Radian",
	url: process.env.NEXT_PUBLIC_WEBSITE_URL!,
	keywords: [
		"React",
		"Next",
		"Next JS",
		"Tailwind CSS",
		"Radian",
		"Radian Components",
		"Radianos Components",
		"Radianui Components",
		"Radian UI",
		"Next JS",
		"Components",
		"UI Kit",
		"UI Design System",
		"RadianOS",
		"Radian OS",
	],
	ogImage: `${process.env.NEXT_PUBLIC_WEBSITE_URL}/og/static-og.png`,
}
