Radian-os/radianos-blocks:
  - source: apps/website/src/registry/ui/
    dest: src/registry/ui/
  - source: apps/website/src/css/
    dest: src/css/
  - source: apps/website/src/registry/animated/
    dest: src/registry/animated/
