Radian-os/radianos-blocks@dev:
  - source: apps/website/src/registry/ui/
    dest: src/components/ui/
  - source: apps/website/src/css/
    dest: src/css/
  - source: apps/website/src/registry/animated/
    dest: src/components/animated/
