import fs from "fs"
import path from "path"

const blocksDir = path.join(process.cwd(), "src/registry/blocks-example")
let indexContent = `// @ts-nocheck
// This file is generated by scripts/generate-blocks-index.ts
// Do not edit this file manually
import * as React from "react"

export type RegistryItem = {
  name: string
  type: "block" | "components"
  files: {
    path: string
    name: string
    type: "page" | "components"
    target?: string
  }[]
  component: React.LazyExoticComponent<React.ComponentType<any>>
}

export const Index: Record<string, RegistryItem> = {\n`

const dirs = fs
	.readdirSync(blocksDir, { withFileTypes: true })
	.filter((dirent) => dirent.isDirectory())

for (let i = 0; i < dirs.length; i++) {
	const dir = dirs[i]
	const blockName = dir.name
	const blockPath = path.join(blocksDir, blockName)

	const files: { path: string; type: string; target?: string; name: string }[] =
		[]

	function walk(currentPath: string) {
		const entries = fs.readdirSync(currentPath, { withFileTypes: true })
		for (const entry of entries) {
			const fullPath = path.join(currentPath, entry.name)
			if (entry.isDirectory()) {
				walk(fullPath)
			} else if (
				entry.isFile() &&
				(entry.name.endsWith(".tsx") ||
					entry.name.endsWith(".ts") ||
					entry.name.endsWith(".css"))
			) {
				// e.g., registry/blocks-example/sidebar-05-default/page.tsx
				const relativeToSrc = path.relative(
					path.join(process.cwd(), "src"),
					fullPath
				)

				const type =
					entry.name === "page.tsx" || entry.name === "layout.tsx"
						? "page"
						: "components"
				if (type === "components") {
					files.push({
						path: relativeToSrc,
						name: entry.name,
						type,
						target: "",
					})
				} else {
					files.push({
						path: relativeToSrc,
						name: entry.name,
						type,
					})
				}
			}
		}
	}

	walk(blockPath)

	indexContent += `  "${blockName}": {
    name: "${blockName}",
    type: "block",
    files: ${JSON.stringify(files, null, 6).replace(/\n/g, "\n    ").trim()},
    component: React.lazy(() => import("@/registry/blocks-example/${blockName}/page"))
  }`

	if (i < dirs.length - 1) {
		indexContent += `,\n`
	} else {
		indexContent += `\n`
	}
}

indexContent += `}\n`

fs.writeFileSync(path.join(blocksDir, "index.tsx"), indexContent)
console.log("Generated src/registry/blocks-example/index.tsx")
