// scripts/build-registry-map.ts
// Run with: tsx scripts/build-registry-map.ts
import * as fs from "fs"
import * as path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const REGISTRY_DIR = path.resolve(__dirname, "../registry/example")
const OUTPUT_FILE = path.resolve(__dirname, "../registry/registry-map.ts")

function getFiles(dir: string, base: string = dir): string[] {
	const entries = fs.readdirSync(dir, { withFileTypes: true })
	return entries.flatMap((entry) => {
		const fullPath = path.join(dir, entry.name)
		if (entry.isDirectory()) return getFiles(fullPath, base)
		if (entry.isFile() && entry.name.endsWith(".tsx")) return [fullPath]
		return []
	})
}

function toKey(fullPath: string): string {
	return path.basename(fullPath, ".tsx")
}

function toImportPath(fullPath: string): string {
	const rel = path.relative(path.resolve(__dirname, "../"), fullPath)
	return "@/" + rel.replace(/\\/g, "/").replace(/\.tsx$/, "")
}

function generate() {
	const files = getFiles(REGISTRY_DIR)

	const entries = files
		.map((file) => {
			const key = toKey(file)
			const importPath = toImportPath(file)
			return `  "${key}": React.lazy(() => import("${importPath}")),`
		})
		.join("\n")

	const output = `// This file is autogenerated by scripts/build-registry-map.ts
// Do not edit this file directly.
import * as React from "react"

const registry: Record<string, React.LazyExoticComponent<React.ComponentType>> = {
${entries}
}

export default registry
`

	fs.writeFileSync(OUTPUT_FILE, output, "utf-8")
	console.log(
		`Registry map generated with ${files.length} components → ${OUTPUT_FILE}`
	)
}

generate()
