// scripts/build-registry-map.ts
// Run with: tsx scripts/build-registry-map.ts
import * as fs from "fs"
import * as path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const REGISTRY_DIR = path.resolve(__dirname, "../registry/example")
const OUTPUT_FILE = path.resolve(__dirname, "../registry/registry-map.ts")
const LOADERS_DIR = path.resolve(__dirname, "../registry/example-loaders")

function getFiles(dir: string, base: string = dir): string[] {
	const entries = fs.readdirSync(dir, { withFileTypes: true })
	return entries.flatMap((entry) => {
		const fullPath = path.join(dir, entry.name)
		if (entry.isDirectory()) return getFiles(fullPath, base)
		if (entry.isFile() && entry.name.endsWith(".tsx")) return [fullPath]
		return []
	})
}

function toKey(fullPath: string): string {
	return path.basename(fullPath, ".tsx")
}

function toGroupName(fullPath: string): string {
	const rel = path.relative(REGISTRY_DIR, fullPath)
	return rel.split(path.sep)[0]
}

function toImportPath(fullPath: string): string {
	const rel = path.relative(path.resolve(__dirname, "../"), fullPath)
	return "@/" + rel.replace(/\\/g, "/").replace(/\.tsx$/, "")
}

function generate() {
	const files = getFiles(REGISTRY_DIR)
	const groups = new Map<string, string[]>()

	for (const file of files) {
		const groupName = toGroupName(file)
		const groupExamples = groups.get(groupName) ?? []
		groupExamples.push(toKey(file))
		groups.set(groupName, groupExamples)
	}

	fs.rmSync(LOADERS_DIR, { recursive: true, force: true })
	fs.mkdirSync(LOADERS_DIR, { recursive: true })

	for (const [groupName] of groups) {
		const entries = files
			.filter((file) => toGroupName(file) === groupName)
			.map(
				(file) =>
					`  "${toKey(file)}": React.lazy(() => import("${toImportPath(file)}")),`
			)
			.join("\n")
		fs.writeFileSync(
			path.join(LOADERS_DIR, `${groupName}.ts`),
			`// Autogenerated by generate-example-registry.ts\nimport * as React from "react"\n\nconst registry: Record<string, React.LazyExoticComponent<React.ComponentType>> = {\n${entries}\n}\n\nexport default registry\n`,
			"utf-8"
		)
	}

	const groupLoaders = Array.from(groups.keys())
		.map((name) => `  "${name}": () => import("./example-loaders/${name}"),`)
		.join("\n")
	const nameToGroup = Array.from(groups.entries())
		.flatMap(([group, examples]) =>
			examples.map((name) => `  "${name}": "${group}",`)
		)
		.join("\n")

	const groupEntries = Array.from(groups.entries())
		.map(([name, examples]) => {
			const exampleEntries = examples
				.map((example) => `"${example}"`)
				.join(", ")

			return `  { name: "${name}", examples: [${exampleEntries}] },`
		})
		.join("\n")

	const output = `// This file is autogenerated by scripts/build-registry-map.ts
// Do not edit this file directly.
import * as React from "react"

export type RegistryExampleGroup = {
  name: string
  examples: string[]
}

const groupLoaders = {
${groupLoaders}
}

const nameToGroup: Record<string, keyof typeof groupLoaders> = {
${nameToGroup}
}

export function getComponent(path: string) {
  const [groupFromPath, nameFromPath] = path.split("/")
  const name = nameFromPath ?? groupFromPath
  const group = (nameFromPath ? groupFromPath : nameToGroup[name]) as keyof typeof groupLoaders | undefined
  const loadGroup = group && groupLoaders[group]

  if (!loadGroup) return null

  return React.lazy(async () => {
    const registry = (await loadGroup()).default
    return { default: registry[name] ?? (() => null) }
  })
}

export const registryExampleGroups: RegistryExampleGroup[] = [
${groupEntries}
]

`

	fs.writeFileSync(OUTPUT_FILE, output, "utf-8")
	console.log(
		`Registry map generated with ${files.length} components → ${OUTPUT_FILE}`
	)
}

generate()
