// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"accordion-box": React.lazy(
		() => import("@/registry/example/accordion/accordion-box")
	),
	"accordion-disable": React.lazy(
		() => import("@/registry/example/accordion/accordion-disable")
	),
	"accordion-indicator": React.lazy(
		() => import("@/registry/example/accordion/accordion-indicator")
	),
	"accordion-nested": React.lazy(
		() => import("@/registry/example/accordion/accordion-nested")
	),
	"accordion-open": React.lazy(
		() => import("@/registry/example/accordion/accordion-open")
	),
	"accordion-preview": React.lazy(
		() => import("@/registry/example/accordion/accordion-preview")
	),
	"accordion-table": React.lazy(
		() => import("@/registry/example/accordion/accordion-table")
	),
	"accordion-with-avatar": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-avatar")
	),
	"accordion-with-chevron-left": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-chevron-left")
	),
	"accordion-with-dotted-line": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-dotted-line")
	),
	"accordion-with-icon": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-icon")
	),
	"accordion-with-sub-header-chevron": React.lazy(
		() =>
			import("@/registry/example/accordion/accordion-with-sub-header-chevron")
	),
}

export default registry
