// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"alert-dialog-preview": React.lazy(
		() => import("@/registry/example/alert-dialog/alert-dialog-preview")
	),
	"backdrop-blur": React.lazy(
		() => import("@/registry/example/alert-dialog/backdrop-blur")
	),
	"backdrop-transparent": React.lazy(
		() => import("@/registry/example/alert-dialog/backdrop-transparent")
	),
	"destructive-alert-dialog": React.lazy(
		() => import("@/registry/example/alert-dialog/destructive-alert-dialog")
	),
	"destructive-dialog-center": React.lazy(
		() => import("@/registry/example/alert-dialog/destructive-dialog-center")
	),
	"destructive-dialog-with-divider": React.lazy(
		() =>
			import("@/registry/example/alert-dialog/destructive-dialog-with-divider")
	),
}

export default registry
