// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"alert-close-example-preview": React.lazy(
		() => import("@/registry/example/alert/alert-close-example-preview")
	),
	"alert-colors-example": React.lazy(
		() => import("@/registry/example/alert/alert-colors-example")
	),
	"alert-error-examples": React.lazy(
		() => import("@/registry/example/alert/alert-error-examples")
	),
	"alert-info-examples": React.lazy(
		() => import("@/registry/example/alert/alert-info-examples")
	),
	"alert-preview": React.lazy(
		() => import("@/registry/example/alert/alert-preview")
	),
	"alert-success-examples": React.lazy(
		() => import("@/registry/example/alert/alert-success-examples")
	),
	"alert-variants-example": React.lazy(
		() => import("@/registry/example/alert/alert-variants-example")
	),
	"alert-warning-example": React.lazy(
		() => import("@/registry/example/alert/alert-warning-example")
	),
}

export default registry
