// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"area-chart-preview": React.lazy(
		() => import("@/registry/example/area-chart/area-chart-preview")
	),
}

export default registry
