// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"aspect-ratio-1-1": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-1-1")
	),
	"aspect-ratio-4-3": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-4-3")
	),
	"aspect-ratio-9-16": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-9-16")
	),
	"aspect-ratio-preview-16-9": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-preview-16-9")
	),
}

export default registry
