// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"account-verified": React.lazy(
		() => import("@/registry/example/auth-blocks/account-verified")
	),
	"email-code": React.lazy(
		() => import("@/registry/example/auth-blocks/email-code")
	),
	"email-verofy": React.lazy(
		() => import("@/registry/example/auth-blocks/email-verofy")
	),
	signin: React.lazy(() => import("@/registry/example/auth-blocks/signin")),
	signup: React.lazy(() => import("@/registry/example/auth-blocks/signup")),
}

export default registry
