// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"avatar-fallback": React.lazy(
		() => import("@/registry/example/avatar/avatar-fallback")
	),
	"avatar-group": React.lazy(
		() => import("@/registry/example/avatar/avatar-group")
	),
	"avatar-preview": React.lazy(
		() => import("@/registry/example/avatar/avatar-preview")
	),
	"avatar-rounded-square": React.lazy(
		() => import("@/registry/example/avatar/avatar-rounded-square")
	),
	"avatar-size": React.lazy(
		() => import("@/registry/example/avatar/avatar-size")
	),
	"avatar-status": React.lazy(
		() => import("@/registry/example/avatar/avatar-status")
	),
	"custom-avatar-with-badge": React.lazy(
		() => import("@/registry/example/avatar/custom-avatar-with-badge")
	),
	"custom-avatar-with-ring": React.lazy(
		() => import("@/registry/example/avatar/custom-avatar-with-ring")
	),
	"custom-avatar-with-status": React.lazy(
		() => import("@/registry/example/avatar/custom-avatar-with-status")
	),
}

export default registry
