// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"badge-avatar-example": React.lazy(
		() => import("@/registry/example/badge/badge-avatar-example")
	),
	"badge-color-example": React.lazy(
		() => import("@/registry/example/badge/badge-color-example")
	),
	"badge-cross-example": React.lazy(
		() => import("@/registry/example/badge/badge-cross-example")
	),
	"badge-dot-example": React.lazy(
		() => import("@/registry/example/badge/badge-dot-example")
	),
	"badge-example": React.lazy(
		() => import("@/registry/example/badge/badge-example")
	),
	"badge-icon-example": React.lazy(
		() => import("@/registry/example/badge/badge-icon-example")
	),
	"badge-interactive-example": React.lazy(
		() => import("@/registry/example/badge/badge-interactive-example")
	),
	"badge-nested-example": React.lazy(
		() => import("@/registry/example/badge/badge-nested-example")
	),
	"badge-rounded-example": React.lazy(
		() => import("@/registry/example/badge/badge-rounded-example")
	),
	"badge-size-example": React.lazy(
		() => import("@/registry/example/badge/badge-size-example")
	),
	"badge-variants-example": React.lazy(
		() => import("@/registry/example/badge/badge-variants-example")
	),
	"badge-with-emoji": React.lazy(
		() => import("@/registry/example/badge/badge-with-emoji")
	),
	"badge-with-flag": React.lazy(
		() => import("@/registry/example/badge/badge-with-flag")
	),
}

export default registry
