// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"banner-black-friday-example": React.lazy(
		() => import("@/registry/example/banner/banner-black-friday-example")
	),
	"banner-color-example": React.lazy(
		() => import("@/registry/example/banner/banner-color-example")
	),
	"banner-error-example": React.lazy(
		() => import("@/registry/example/banner/banner-error-example")
	),
	"banner-example-preview": React.lazy(
		() => import("@/registry/example/banner/banner-example-preview")
	),
	"banner-floating-example": React.lazy(
		() => import("@/registry/example/banner/banner-floating-example")
	),
	"banner-primary-example": React.lazy(
		() => import("@/registry/example/banner/banner-primary-example")
	),
	"banner-success-example": React.lazy(
		() => import("@/registry/example/banner/banner-success-example")
	),
	"banner-variants-example": React.lazy(
		() => import("@/registry/example/banner/banner-variants-example")
	),
}

export default registry
