// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"bar-chart-horizontal": React.lazy(
		() => import("@/registry/example/bar-chart/bar-chart-horizontal")
	),
	"bar-chart-label": React.lazy(
		() => import("@/registry/example/bar-chart/bar-chart-label")
	),
	"bar-chart-multiple": React.lazy(
		() => import("@/registry/example/bar-chart/bar-chart-multiple")
	),
	"bar-chart-negative": React.lazy(
		() => import("@/registry/example/bar-chart/bar-chart-negative")
	),
	"bar-chart-preview": React.lazy(
		() => import("@/registry/example/bar-chart/bar-chart-preview")
	),
	"bar-chart-stacked": React.lazy(
		() => import("@/registry/example/bar-chart/bar-chart-stacked")
	),
}

export default registry
