// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"breadcrumb-card-design": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-card-design")
	),
	"breadcrumb-preview": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-preview")
	),
	"breadcrumb-with-dot": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-dot")
	),
	"breadcrumb-with-dropdown": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-dropdown")
	),
	"breadcrumb-with-icons": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-icons")
	),
	"breadcrumb-with-slash": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-slash")
	),
}

export default registry
