// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"button-colors-example": React.lazy(
		() => import("@/registry/example/button/button-colors-example")
	),
	"button-compact-example": React.lazy(
		() => import("@/registry/example/button/button-compact-example")
	),
	"button-elevated-example": React.lazy(
		() => import("@/registry/example/button/button-elevated-example")
	),
	"button-example-disabled": React.lazy(
		() => import("@/registry/example/button/button-example-disabled")
	),
	"button-example-preview": React.lazy(
		() => import("@/registry/example/button/button-example-preview")
	),
	"button-example-rounded": React.lazy(
		() => import("@/registry/example/button/button-example-rounded")
	),
	"button-fancy-example": React.lazy(
		() => import("@/registry/example/button/button-fancy-example")
	),
	"button-glossy-example": React.lazy(
		() => import("@/registry/example/button/button-glossy-example")
	),
	"button-group-example": React.lazy(
		() => import("@/registry/example/button/button-group-example")
	),
	"button-input-example": React.lazy(
		() => import("@/registry/example/button/button-input-example")
	),
	"button-size-example": React.lazy(
		() => import("@/registry/example/button/button-size-example")
	),
	"button-smooth-example": React.lazy(
		() => import("@/registry/example/button/button-smooth-example")
	),
	"button-split-example": React.lazy(
		() => import("@/registry/example/button/button-split-example")
	),
	"button-variants-example": React.lazy(
		() => import("@/registry/example/button/button-variants-example")
	),
	"button-with-badge-example": React.lazy(
		() => import("@/registry/example/button/button-with-badge-example")
	),
	"button-with-icon-example": React.lazy(
		() => import("@/registry/example/button/button-with-icon-example")
	),
	"icon-button-example": React.lazy(
		() => import("@/registry/example/button/icon-button-example")
	),
	"link-button-example": React.lazy(
		() => import("@/registry/example/button/link-button-example")
	),
	"loading-button-example": React.lazy(
		() => import("@/registry/example/button/loading-button-example")
	),
	"social-button-example": React.lazy(
		() => import("@/registry/example/button/social-button-example")
	),
	"svg-button-example": React.lazy(
		() => import("@/registry/example/button/svg-button-example")
	),
}

export default registry
