// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"calendar-footer-preview": React.lazy(
		() => import("@/registry/example/calendar/calendar-footer-preview")
	),
	"calendar-preview": React.lazy(
		() => import("@/registry/example/calendar/calendar-preview")
	),
	"calendar-scrollable-time": React.lazy(
		() => import("@/registry/example/calendar/calendar-scrollable-time")
	),
	"calendar-time-input": React.lazy(
		() => import("@/registry/example/calendar/calendar-time-input")
	),
	"calendar-year-month-selector-example": React.lazy(
		() =>
			import("@/registry/example/calendar/calendar-year-month-selector-example")
	),
	"multiple-months-calendar-example": React.lazy(
		() => import("@/registry/example/calendar/multiple-months-calendar-example")
	),
	"quick-selection-preview": React.lazy(
		() => import("@/registry/example/calendar/quick-selection-preview")
	),
	"time-picker-calendar-preview": React.lazy(
		() => import("@/registry/example/calendar/time-picker-calendar-preview")
	),
}

export default registry
