// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"card-billing-example": React.lazy(
		() => import("@/registry/example/card/card-billing-example")
	),
	"card-dashboard-example": React.lazy(
		() => import("@/registry/example/card/card-dashboard-example")
	),
	"card-default-example": React.lazy(
		() => import("@/registry/example/card/card-default-example")
	),
	"card-fancy-example": React.lazy(
		() => import("@/registry/example/card/card-fancy-example")
	),
	"card-feature-example": React.lazy(
		() => import("@/registry/example/card/card-feature-example")
	),
	"card-header-footer-example": React.lazy(
		() => import("@/registry/example/card/card-header-footer-example")
	),
	"card-info-example": React.lazy(
		() => import("@/registry/example/card/card-info-example")
	),
	"card-signin-example": React.lazy(
		() => import("@/registry/example/card/card-signin-example")
	),
	"card-with-image-example": React.lazy(
		() => import("@/registry/example/card/card-with-image-example")
	),
}

export default registry
