// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"carousel-autoplay": React.lazy(
		() => import("@/registry/example/carousel/carousel-autoplay")
	),
	"carousel-dotbutton": React.lazy(
		() => import("@/registry/example/carousel/carousel-dotbutton")
	),
	"carousel-loop": React.lazy(
		() => import("@/registry/example/carousel/carousel-loop")
	),
	"carousel-orientation": React.lazy(
		() => import("@/registry/example/carousel/carousel-orientation")
	),
	"carousel-preview": React.lazy(
		() => import("@/registry/example/carousel/carousel-preview")
	),
	"carousel-scale": React.lazy(
		() => import("@/registry/example/carousel/carousel-scale")
	),
	"carousel-size": React.lazy(
		() => import("@/registry/example/carousel/carousel-size")
	),
	"carousel-space": React.lazy(
		() => import("@/registry/example/carousel/carousel-space")
	),
}

export default registry
