// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"chart-preview": React.lazy(
		() => import("@/registry/example/chart/chart-preview")
	),
}

export default registry
