// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"checkbox-card": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-card")
	),
	"checkbox-checked": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-checked")
	),
	"checkbox-disabled": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-disabled")
	),
	"checkbox-dropdown": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-dropdown")
	),
	"checkbox-form": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-form")
	),
	"checkbox-group": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-group")
	),
	"checkbox-preview": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-preview")
	),
	"checkbox-setup": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-setup")
	),
	"checkbox-size": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-size")
	),
	"indeterminate-checkbox": React.lazy(
		() => import("@/registry/example/checkbox/indeterminate-checkbox")
	),
}

export default registry
