// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"code-area-preview": React.lazy(
		() => import("@/registry/example/code-area/code-area-preview")
	),
	"code-language-javascript-example": React.lazy(
		() =>
			import("@/registry/example/code-area/code-language-javascript-example")
	),
	"code-language-python-example": React.lazy(
		() => import("@/registry/example/code-area/code-language-python-example")
	),
	"code-language-typescript-example": React.lazy(
		() =>
			import("@/registry/example/code-area/code-language-typescript-example")
	),
	"code-theme-example": React.lazy(
		() => import("@/registry/example/code-area/code-theme-example")
	),
	"code-with-copy-example": React.lazy(
		() => import("@/registry/example/code-area/code-with-copy-example")
	),
	"code-with-tabs-preview": React.lazy(
		() => import("@/registry/example/code-area/code-with-tabs-preview")
	),
}

export default registry
