// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"collapsible-accordion": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-accordion")
	),
	"collapsible-billing-card": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-billing-card")
	),
	"collapsible-dropdown": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-dropdown")
	),
	"collapsible-list": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-list")
	),
	"collapsible-menu": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-menu")
	),
	"collapsible-preview": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-preview")
	),
	"collapsible-radio": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-radio")
	),
	"collapsible-text": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-text")
	),
}

export default registry
