// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"combobox-email-invite": React.lazy(
		() => import("@/registry/example/combobox/combobox-email-invite")
	),
	"combobox-form": React.lazy(
		() => import("@/registry/example/combobox/combobox-form")
	),
	"combobox-multiselect": React.lazy(
		() => import("@/registry/example/combobox/combobox-multiselect")
	),
	"combobox-preview": React.lazy(
		() => import("@/registry/example/combobox/combobox-preview")
	),
	"combobox-timezone": React.lazy(
		() => import("@/registry/example/combobox/combobox-timezone")
	),
	"virtualized-list": React.lazy(
		() => import("@/registry/example/combobox/virtualized-list")
	),
}

export default registry
