// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"command-preview": React.lazy(
		() => import("@/registry/example/command/command-preview")
	),
	"command-search-contact": React.lazy(
		() => import("@/registry/example/command/command-search-contact")
	),
	"command-search-integration": React.lazy(
		() => import("@/registry/example/command/command-search-integration")
	),
	"command-system": React.lazy(
		() => import("@/registry/example/command/command-system")
	),
}

export default registry
