// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"context-menu-checkbox": React.lazy(
		() => import("@/registry/example/context-menu/context-menu-checkbox")
	),
	"context-menu-dialog": React.lazy(
		() => import("@/registry/example/context-menu/context-menu-dialog")
	),
	"context-menu-keyboard": React.lazy(
		() => import("@/registry/example/context-menu/context-menu-keyboard")
	),
	"context-menu-preview": React.lazy(
		() => import("@/registry/example/context-menu/context-menu-preview")
	),
	"context-menu-submenu": React.lazy(
		() => import("@/registry/example/context-menu/context-menu-submenu")
	),
}

export default registry
