// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"currency-decimal-separator": React.lazy(
		() => import("@/registry/example/currency-input/currency-decimal-separator")
	),
	"currency-decimals-limit": React.lazy(
		() => import("@/registry/example/currency-input/currency-decimals-limit")
	),
	"currency-input-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-input-example")
	),
	"currency-locale-config": React.lazy(
		() => import("@/registry/example/currency-input/currency-locale-config")
	),
	"currency-max-value-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-max-value-example")
	),
	"currency-nodecimal-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-nodecimal-example")
	),
	"currency-prefix-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-prefix-example")
	),
	"currency-select-with-custom-prefix": React.lazy(
		() =>
			import("@/registry/example/currency-input/currency-select-with-custom-prefix")
	),
	"currency-separators-example": React.lazy(
		() =>
			import("@/registry/example/currency-input/currency-separators-example")
	),
	"currency-step-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-step-example")
	),
	"currency-with-input-group": React.lazy(
		() => import("@/registry/example/currency-input/currency-with-input-group")
	),
	"currency-with-input-wrapper": React.lazy(
		() =>
			import("@/registry/example/currency-input/currency-with-input-wrapper")
	),
	"currency-with-prefix": React.lazy(
		() => import("@/registry/example/currency-input/currency-with-prefix")
	),
}

export default registry
