// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"date-picker-form": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-form")
	),
	"date-picker-input": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-input")
	),
	"date-picker-preview": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-preview")
	),
	"date-picker-range-example": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-range-example")
	),
	"date-picker-with-time": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-with-time")
	),
}

export default registry
