// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"dialog-backdrop-blur": React.lazy(
		() => import("@/registry/example/dialog/dialog-backdrop-blur")
	),
	"dialog-backdrop-transparent": React.lazy(
		() => import("@/registry/example/dialog/dialog-backdrop-transparent")
	),
	"dialog-backdrop-white-overlay": React.lazy(
		() => import("@/registry/example/dialog/dialog-backdrop-white-overlay")
	),
	"dialog-close-button-hidden": React.lazy(
		() => import("@/registry/example/dialog/dialog-close-button-hidden")
	),
	"dialog-destructive": React.lazy(
		() => import("@/registry/example/dialog/dialog-destructive")
	),
	"dialog-preview": React.lazy(
		() => import("@/registry/example/dialog/dialog-preview")
	),
	"dialog-with-form": React.lazy(
		() => import("@/registry/example/dialog/dialog-with-form")
	),
	"dialog-with-radio-cards": React.lazy(
		() => import("@/registry/example/dialog/dialog-with-radio-cards")
	),
	"dialog-without-divider": React.lazy(
		() => import("@/registry/example/dialog/dialog-without-divider")
	),
}

export default registry
