// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"divider-badge-preview": React.lazy(
		() => import("@/registry/example/divider/divider-badge-preview")
	),
	"divider-plain-text-preview": React.lazy(
		() => import("@/registry/example/divider/divider-plain-text-preview")
	),
	"divider-preview": React.lazy(
		() => import("@/registry/example/divider/divider-preview")
	),
	"divider-text-preview": React.lazy(
		() => import("@/registry/example/divider/divider-text-preview")
	),
}

export default registry
