// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"drawer-backdrop-example": React.lazy(
		() => import("@/registry/example/drawer/drawer-backdrop-example")
	),
	"drawer-example-preview": React.lazy(
		() => import("@/registry/example/drawer/drawer-example-preview")
	),
	"drawer-handle-preview": React.lazy(
		() => import("@/registry/example/drawer/drawer-handle-preview")
	),
	"drawer-position-example": React.lazy(
		() => import("@/registry/example/drawer/drawer-position-example")
	),
	"drawer-variant-example": React.lazy(
		() => import("@/registry/example/drawer/drawer-variant-example")
	),
}

export default registry
