// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"dropdown-preview": React.lazy(
		() => import("@/registry/example/dropdown-menu/dropdown-preview")
	),
	"dropdown-with-checkbox-example": React.lazy(
		() =>
			import("@/registry/example/dropdown-menu/dropdown-with-checkbox-example")
	),
	"dropdown-with-dropdown-checkbox": React.lazy(
		() =>
			import("@/registry/example/dropdown-menu/dropdown-with-dropdown-checkbox")
	),
	"dropdown-with-radio": React.lazy(
		() => import("@/registry/example/dropdown-menu/dropdown-with-radio")
	),
	"user-profile-dropdown-example": React.lazy(
		() =>
			import("@/registry/example/dropdown-menu/user-profile-dropdown-example")
	),
}

export default registry
