// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"empty-preview": React.lazy(
		() => import("@/registry/example/empty/empty-preview")
	),
	"no-comments-yet": React.lazy(
		() => import("@/registry/example/empty/no-comments-yet")
	),
	"no-files-uploaded": React.lazy(
		() => import("@/registry/example/empty/no-files-uploaded")
	),
	"no-internet-connection": React.lazy(
		() => import("@/registry/example/empty/no-internet-connection")
	),
	"no-messages": React.lazy(
		() => import("@/registry/example/empty/no-messages")
	),
	"no-notifications": React.lazy(
		() => import("@/registry/example/empty/no-notifications")
	),
	"no-projects-yet": React.lazy(
		() => import("@/registry/example/empty/no-projects-yet")
	),
	"no-recent-activity": React.lazy(
		() => import("@/registry/example/empty/no-recent-activity")
	),
	"no-reports-yet": React.lazy(
		() => import("@/registry/example/empty/no-reports-yet")
	),
	"no-search-results": React.lazy(
		() => import("@/registry/example/empty/no-search-results")
	),
	"no-such-directory": React.lazy(
		() => import("@/registry/example/empty/no-such-directory")
	),
	"unexpected-error": React.lazy(
		() => import("@/registry/example/empty/unexpected-error")
	),
}

export default registry
