// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"file-upload-avatar": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-avatar")
	),
	"file-upload-document": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-document")
	),
	"file-upload-example": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-example")
	),
	"file-upload-image": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-image")
	),
	"file-upload-preview": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-preview")
	),
}

export default registry
