// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"flag-country-select": React.lazy(
		() => import("@/registry/example/flag/flag-country-select")
	),
	"flag-preview": React.lazy(
		() => import("@/registry/example/flag/flag-preview")
	),
	"flag-shapes": React.lazy(
		() => import("@/registry/example/flag/flag-shapes")
	),
	"flag-sizes": React.lazy(() => import("@/registry/example/flag/flag-sizes")),
}

export default registry
