// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"form-preview": React.lazy(
		() => import("@/registry/example/form/form-preview")
	),
	"sign-in-form": React.lazy(
		() => import("@/registry/example/form/sign-in-form")
	),
	"sign-up-form": React.lazy(
		() => import("@/registry/example/form/sign-up-form")
	),
}

export default registry
