// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"hover-card-group-quick-view": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-group-quick-view")
	),
	"hover-card-influencer-profile": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-influencer-profile")
	),
	"hover-card-post-images-and-stats": React.lazy(
		() =>
			import("@/registry/example/hover-card/hover-card-post-images-and-stats")
	),
	"hover-card-preview": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-preview")
	),
	"hover-card-user-mini-profile": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-user-mini-profile")
	),
}

export default registry
