// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"credit-card-input-preview": React.lazy(
		() => import("@/registry/example/input/credit-card-input-preview")
	),
	"disabled-input": React.lazy(
		() => import("@/registry/example/input/disabled-input")
	),
	"email-input-preview": React.lazy(
		() => import("@/registry/example/input/email-input-preview")
	),
	"input-clear-button": React.lazy(
		() => import("@/registry/example/input/input-clear-button")
	),
	"input-color": React.lazy(
		() => import("@/registry/example/input/input-color")
	),
	"input-date": React.lazy(() => import("@/registry/example/input/input-date")),
	"input-form": React.lazy(() => import("@/registry/example/input/input-form")),
	"input-groups": React.lazy(
		() => import("@/registry/example/input/input-groups")
	),
	"input-preview": React.lazy(
		() => import("@/registry/example/input/input-preview")
	),
	"input-search-suggestions": React.lazy(
		() => import("@/registry/example/input/input-search-suggestions")
	),
	"input-search": React.lazy(
		() => import("@/registry/example/input/input-search")
	),
	"input-size": React.lazy(() => import("@/registry/example/input/input-size")),
	"input-wrapper": React.lazy(
		() => import("@/registry/example/input/input-wrapper")
	),
	"invalid-input": React.lazy(
		() => import("@/registry/example/input/invalid-input")
	),
	"number-input-preview": React.lazy(
		() => import("@/registry/example/input/number-input-preview")
	),
	"password-preview": React.lazy(
		() => import("@/registry/example/input/password-preview")
	),
	"password-toggle-on-focus": React.lazy(
		() => import("@/registry/example/input/password-toggle-on-focus")
	),
	"password-toggle-visible": React.lazy(
		() => import("@/registry/example/input/password-toggle-visible")
	),
	"password-validation-example": React.lazy(
		() => import("@/registry/example/input/password-validation-example")
	),
	"url-input-preview": React.lazy(
		() => import("@/registry/example/input/url-input-preview")
	),
}

export default registry
