// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"menubar-preview": React.lazy(
		() => import("@/registry/example/menubar/menubar-preview")
	),
	"menubar-text-editor-example": React.lazy(
		() => import("@/registry/example/menubar/menubar-text-editor-example")
	),
	"menubar-with-destructive-example": React.lazy(
		() => import("@/registry/example/menubar/menubar-with-destructive-example")
	),
	"menubar-with-radio-example": React.lazy(
		() => import("@/registry/example/menubar/menubar-with-radio-example")
	),
}

export default registry
