// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"navigation-menu-align": React.lazy(
		() => import("@/registry/example/navigation-menu/navigation-menu-align")
	),
	"navigation-menu-columns": React.lazy(
		() => import("@/registry/example/navigation-menu/navigation-menu-columns")
	),
	"navigation-menu-plain": React.lazy(
		() => import("@/registry/example/navigation-menu/navigation-menu-plain")
	),
	"navigation-menu-preview": React.lazy(
		() => import("@/registry/example/navigation-menu/navigation-menu-preview")
	),
}

export default registry
