// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"otp-field-auto-submit": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-auto-submit")
	),
	"otp-field-disabled": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-disabled")
	),
	"otp-field-form": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-form")
	),
	"otp-field-preview": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-preview")
	),
	"otp-field-type-password": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-type-password")
	),
	"otp-field-validation-type": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-validation-type")
	),
	"otp-size": React.lazy(() => import("@/registry/example/otp-field/otp-size")),
}

export default registry
