// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"pagination-card-example": React.lazy(
		() => import("@/registry/example/pagination/pagination-card-example")
	),
	"pagination-example-preview": React.lazy(
		() => import("@/registry/example/pagination/pagination-example-preview")
	),
	"pagination-text-example": React.lazy(
		() => import("@/registry/example/pagination/pagination-text-example")
	),
	"rows-per-page-example": React.lazy(
		() => import("@/registry/example/pagination/rows-per-page-example")
	),
}

export default registry
