// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"exclude-countries-example": React.lazy(
		() =>
			import("@/registry/example/phone-number-input/exclude-countries-example")
	),
	"international-phone-hook-example": React.lazy(
		() =>
			import(
				"@/registry/example/phone-number-input/international-phone-hook-example"
			)
	),
	"national-phone-number-example": React.lazy(
		() =>
			import(
				"@/registry/example/phone-number-input/national-phone-number-example"
			)
	),
	"only-countries-phone": React.lazy(
		() => import("@/registry/example/phone-number-input/only-countries-phone")
	),
	"phone-number-example": React.lazy(
		() => import("@/registry/example/phone-number-input/phone-number-example")
	),
	"phone-number-no-formatting": React.lazy(
		() =>
			import("@/registry/example/phone-number-input/phone-number-no-formatting")
	),
	"phone-number-static": React.lazy(
		() => import("@/registry/example/phone-number-input/phone-number-static")
	),
	"preferred-countries-phone": React.lazy(
		() =>
			import("@/registry/example/phone-number-input/preferred-countries-phone")
	),
}

export default registry
