// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"pie-chart-preview": React.lazy(
		() => import("@/registry/example/pie-chart/pie-chart-preview")
	),
}

export default registry
