// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"pie-chart-label": React.lazy(
		() => import("@/registry/example/pie-chart/pie-chart-label")
	),
	"pie-chart-legend": React.lazy(
		() => import("@/registry/example/pie-chart/pie-chart-legend")
	),
	"pie-chart-preview": React.lazy(
		() => import("@/registry/example/pie-chart/pie-chart-preview")
	),
	"pie-chart-stacked": React.lazy(
		() => import("@/registry/example/pie-chart/pie-chart-stacked")
	),
}

export default registry
