// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"popover-align": React.lazy(
		() => import("@/registry/example/popover/popover-align")
	),
	"popover-emoji": React.lazy(
		() => import("@/registry/example/popover/popover-emoji")
	),
	"popover-emoji2": React.lazy(
		() => import("@/registry/example/popover/popover-emoji2")
	),
	"popover-guide": React.lazy(
		() => import("@/registry/example/popover/popover-guide")
	),
	"popover-preview": React.lazy(
		() => import("@/registry/example/popover/popover-preview")
	),
	"popover-side": React.lazy(
		() => import("@/registry/example/popover/popover-side")
	),
}

export default registry
