// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"downloading-progress": React.lazy(
		() => import("@/registry/example/progress/downloading-progress")
	),
	"progress-example": React.lazy(
		() => import("@/registry/example/progress/progress-example")
	),
	"progress-file-upload": React.lazy(
		() => import("@/registry/example/progress/progress-file-upload")
	),
	"progress-preview": React.lazy(
		() => import("@/registry/example/progress/progress-preview")
	),
}

export default registry
