// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"radio-card": React.lazy(
		() => import("@/registry/example/radio-group/radio-card")
	),
	"radio-dropdown": React.lazy(
		() => import("@/registry/example/radio-group/radio-dropdown")
	),
	"radio-group-disabled": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-disabled")
	),
	"radio-group-form": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-form")
	),
	"radio-group-preview": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-preview")
	),
	"radio-group-size": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-size")
	),
	"radio-horizontal": React.lazy(
		() => import("@/registry/example/radio-group/radio-horizontal")
	),
}

export default registry
