// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"handle-on-hover": React.lazy(
		() => import("@/registry/example/resizable/handle-on-hover")
	),
	"resizable-example": React.lazy(
		() => import("@/registry/example/resizable/resizable-example")
	),
	"resizable-preview": React.lazy(
		() => import("@/registry/example/resizable/resizable-preview")
	),
}

export default registry
