// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"scroll-area-dropdown": React.lazy(
		() => import("@/registry/example/scroll-area/scroll-area-dropdown")
	),
	"scroll-area-horizontal": React.lazy(
		() => import("@/registry/example/scroll-area/scroll-area-horizontal")
	),
	"scroll-area-preview": React.lazy(
		() => import("@/registry/example/scroll-area/scroll-area-preview")
	),
	"scroll-area-vertical": React.lazy(
		() => import("@/registry/example/scroll-area/scroll-area-vertical")
	),
}

export default registry
