// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"select-custom-indicator": React.lazy(
		() => import("@/registry/example/select/select-custom-indicator")
	),
	"select-form": React.lazy(
		() => import("@/registry/example/select/select-form")
	),
	"select-indicator-position": React.lazy(
		() => import("@/registry/example/select/select-indicator-position")
	),
	"select-preview": React.lazy(
		() => import("@/registry/example/select/select-preview")
	),
	"select-sizes": React.lazy(
		() => import("@/registry/example/select/select-sizes")
	),
	"select-time-picker": React.lazy(
		() => import("@/registry/example/select/select-time-picker")
	),
	"select-with-avatar": React.lazy(
		() => import("@/registry/example/select/select-with-avatar")
	),
	"select-with-badge": React.lazy(
		() => import("@/registry/example/select/select-with-badge")
	),
}

export default registry
