// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"skeleton-divided-list": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-divided-list")
	),
	"skeleton-dropdown": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-dropdown")
	),
	"skeleton-gallery": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-gallery")
	),
	"skeleton-multicolumn": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-multicolumn")
	),
	"skeleton-preview": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-preview")
	),
	"skeleton-social-post": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-social-post")
	),
	"skeleton-table-row": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-table-row")
	),
	"skeleton-thumbnail-list": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-thumbnail-list")
	),
}

export default registry
