// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"price-range": React.lazy(
		() => import("@/registry/example/slider/price-range")
	),
	"range-slider": React.lazy(
		() => import("@/registry/example/slider/range-slider")
	),
	"slider-disabled": React.lazy(
		() => import("@/registry/example/slider/slider-disabled")
	),
	"slider-preview": React.lazy(
		() => import("@/registry/example/slider/slider-preview")
	),
	"slider-vertical": React.lazy(
		() => import("@/registry/example/slider/slider-vertical")
	),
	"slider-with-input": React.lazy(
		() => import("@/registry/example/slider/slider-with-input")
	),
	"slider-with-marks": React.lazy(
		() => import("@/registry/example/slider/slider-with-marks")
	),
	"slider-with-stepper": React.lazy(
		() => import("@/registry/example/slider/slider-with-stepper")
	),
	"slider-with-tooltip": React.lazy(
		() => import("@/registry/example/slider/slider-with-tooltip")
	),
}

export default registry
