// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"sonner-expand": React.lazy(
		() => import("@/registry/example/sonner/sonner-expand")
	),
	"sonner-placement": React.lazy(
		() => import("@/registry/example/sonner/sonner-placement")
	),
	"sonner-position": React.lazy(
		() => import("@/registry/example/sonner/sonner-position")
	),
	"sonner-preview": React.lazy(
		() => import("@/registry/example/sonner/sonner-preview")
	),
	"sonner-variant": React.lazy(
		() => import("@/registry/example/sonner/sonner-variant")
	),
}

export default registry
