// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"spinner-badges": React.lazy(
		() => import("@/registry/example/spinner/spinner-badges")
	),
	"spinner-colors": React.lazy(
		() => import("@/registry/example/spinner/spinner-colors")
	),
	"spinner-input-group": React.lazy(
		() => import("@/registry/example/spinner/spinner-input-group")
	),
	"spinner-overlay": React.lazy(
		() => import("@/registry/example/spinner/spinner-overlay")
	),
	"spinner-preview": React.lazy(
		() => import("@/registry/example/spinner/spinner-preview")
	),
	"spinner-sizes": React.lazy(
		() => import("@/registry/example/spinner/spinner-sizes")
	),
}

export default registry
