// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"stepper-bar": React.lazy(
		() => import("@/registry/example/stepper/stepper-bar")
	),
	"stepper-controlled": React.lazy(
		() => import("@/registry/example/stepper/stepper-controlled")
	),
	"stepper-description": React.lazy(
		() => import("@/registry/example/stepper/stepper-description")
	),
	"stepper-icon": React.lazy(
		() => import("@/registry/example/stepper/stepper-icon")
	),
	"stepper-preview": React.lazy(
		() => import("@/registry/example/stepper/stepper-preview")
	),
	"stepper-state": React.lazy(
		() => import("@/registry/example/stepper/stepper-state")
	),
	"stepper-title": React.lazy(
		() => import("@/registry/example/stepper/stepper-title")
	),
	"stepper-vertical": React.lazy(
		() => import("@/registry/example/stepper/stepper-vertical")
	),
}

export default registry
