// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"icon-inside-switch": React.lazy(
		() => import("@/registry/example/switch/icon-inside-switch")
	),
	"square-switch": React.lazy(
		() => import("@/registry/example/switch/square-switch")
	),
	"switch-card": React.lazy(
		() => import("@/registry/example/switch/switch-card")
	),
	"switch-disabled": React.lazy(
		() => import("@/registry/example/switch/switch-disabled")
	),
	"switch-error-card": React.lazy(
		() => import("@/registry/example/switch/switch-error-card")
	),
	"switch-form": React.lazy(
		() => import("@/registry/example/switch/switch-form")
	),
	"switch-icon-indicator": React.lazy(
		() => import("@/registry/example/switch/switch-icon-indicator")
	),
	"switch-on-off": React.lazy(
		() => import("@/registry/example/switch/switch-on-off")
	),
	"switch-preview": React.lazy(
		() => import("@/registry/example/switch/switch-preview")
	),
	"switch-sizes": React.lazy(
		() => import("@/registry/example/switch/switch-sizes")
	),
	"switch-success-card": React.lazy(
		() => import("@/registry/example/switch/switch-success-card")
	),
	"text-switch": React.lazy(
		() => import("@/registry/example/switch/text-switch")
	),
}

export default registry
