// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"basic-data-table": React.lazy(
		() => import("@/registry/example/table/basic-data-table")
	),
	"dragable-table": React.lazy(
		() => import("@/registry/example/table/dragable-table")
	),
	"expand-table": React.lazy(
		() => import("@/registry/example/table/expand-table")
	),
	"resize-table": React.lazy(
		() => import("@/registry/example/table/resize-table")
	),
	"table-example": React.lazy(
		() => import("@/registry/example/table/table-example")
	),
	"table-preview": React.lazy(
		() => import("@/registry/example/table/table-preview")
	),
}

export default registry
