// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"tabs-disabled": React.lazy(
		() => import("@/registry/example/tabs/tabs-disabled")
	),
	"tabs-preview": React.lazy(
		() => import("@/registry/example/tabs/tabs-preview")
	),
	"tabs-variant-ghost": React.lazy(
		() => import("@/registry/example/tabs/tabs-variant-ghost")
	),
	"tabs-variant-open": React.lazy(
		() => import("@/registry/example/tabs/tabs-variant-open")
	),
	"tabs-vertical": React.lazy(
		() => import("@/registry/example/tabs/tabs-vertical")
	),
	"tabs-width-full": React.lazy(
		() => import("@/registry/example/tabs/tabs-width-full")
	),
	"tabs-with-badge": React.lazy(
		() => import("@/registry/example/tabs/tabs-with-badge")
	),
	"tabs-with-icon": React.lazy(
		() => import("@/registry/example/tabs/tabs-with-icon")
	),
}

export default registry
