// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"limited-characters": React.lazy(
		() => import("@/registry/example/text-area/limited-characters")
	),
	"text-area-disabled": React.lazy(
		() => import("@/registry/example/text-area/text-area-disabled")
	),
	"text-area-form": React.lazy(
		() => import("@/registry/example/text-area/text-area-form")
	),
	"text-area-preview": React.lazy(
		() => import("@/registry/example/text-area/text-area-preview")
	),
	"text-area-resizable-false": React.lazy(
		() => import("@/registry/example/text-area/text-area-resizable-false")
	),
}

export default registry
