// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"toggle-disabled": React.lazy(
		() => import("@/registry/example/toggle/toggle-disabled")
	),
	"toggle-favorite": React.lazy(
		() => import("@/registry/example/toggle/toggle-favorite")
	),
	"toggle-formatting-toolbar": React.lazy(
		() => import("@/registry/example/toggle/toggle-formatting-toolbar")
	),
	"toggle-heart": React.lazy(
		() => import("@/registry/example/toggle/toggle-heart")
	),
	"toggle-notification": React.lazy(
		() => import("@/registry/example/toggle/toggle-notification")
	),
	"toggle-preview": React.lazy(
		() => import("@/registry/example/toggle/toggle-preview")
	),
	"toggle-sizes": React.lazy(
		() => import("@/registry/example/toggle/toggle-sizes")
	),
	"toggle-variants": React.lazy(
		() => import("@/registry/example/toggle/toggle-variants")
	),
}

export default registry
