// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"toggle-group-disabled": React.lazy(
		() => import("@/registry/example/toggle-group/toggle-group-disabled")
	),
	"toggle-group-ghost-variant": React.lazy(
		() => import("@/registry/example/toggle-group/toggle-group-ghost-variant")
	),
	"toggle-group-outline-variant": React.lazy(
		() => import("@/registry/example/toggle-group/toggle-group-outline-variant")
	),
	"toggle-group-preview": React.lazy(
		() => import("@/registry/example/toggle-group/toggle-group-preview")
	),
	"toggle-group-spacing": React.lazy(
		() => import("@/registry/example/toggle-group/toggle-group-spacing")
	),
	"toggle-group-vertical": React.lazy(
		() => import("@/registry/example/toggle-group/toggle-group-vertical")
	),
}

export default registry
