// Autogenerated by generate-example-registry.ts
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"tooltip-align": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-align")
	),
	"tooltip-preview": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-preview")
	),
	"tooltip-side": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-side")
	),
	"tooltip-theme": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-theme")
	),
	"tooltip-with-arrow": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-arrow")
	),
	"tooltip-with-chart": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-chart")
	),
	"tooltip-with-icon-title": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-icon-title")
	),
	"tooltip-with-image": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-image")
	),
	"tooltip-with-title-description": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-title-description")
	),
}

export default registry
