export type AccountType = "valid" | "fake"

export interface UserItem {
	id: string
	name: string
	initials: string
	avatarUrl?: string
	address: string
	signedUpAs: AccountType
	email: string
	phone?: string
}

export const USERS_DATA: UserItem[] = [
	{
		id: "user-1",
		name: "Amanda Harvey",
		initials: "AH",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "4222 River Rd, Columbus, 31904, United States",
		signedUpAs: "valid",
		email: "amanda@site.so",
		phone: undefined,
	},
	{
		id: "user-2",
		name: "Rachel Doe",
		initials: "RD",
		address: "2952 S Peoria Ave, Tulsa, 74114, United States",
		signedUpAs: "fake",
		email: "rachel@site.so",
		phone: "+297 000-00-00",
	},
	{
		id: "user-3",
		name: "Costa Quinn",
		initials: "CQ",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "255 Dock Ln, New Tazewell, 37825, United States",
		signedUpAs: "valid",
		email: "costa@site.so",
		phone: "+1 000-00-00",
	},
	{
		id: "user-4",
		name: "Anna Richard",
		initials: "AR",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "4970 Park Ave W, Ohio, 44273, United States",
		signedUpAs: "valid",
		email: "anne@site.so",
		phone: "+1 230-28-00",
	},
	{
		id: "user-5",
		name: "Bob Dean",
		initials: "BD",
		address: "4222 River Rd, Columbus, 31904, United States",
		signedUpAs: "fake",
		email: "bob@site.so",
		phone: "+33 000-00-00",
	},
	{
		id: "user-6",
		name: "Mark Colbert",
		initials: "MC",
		address: "2952 S Peoria Ave, Tulsa, 74114, United States",
		signedUpAs: "valid",
		email: "mark@site.so",
		phone: "+420 000-00-00",
	},
	{
		id: "user-7",
		name: "Finch Hoot",
		initials: "FH",
		address: "1818 H St NW, Washington, 20433, United States",
		signedUpAs: "valid",
		email: "finch@site.so",
		phone: undefined,
	},
	{
		id: "user-8",
		name: "Ella Lauda",
		initials: "EL",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "3 Grace Dr, New Mexico, 08857, United States",
		signedUpAs: "fake",
		email: "ella@site.so",
		phone: "+1 212-00-11",
	},
	{
		id: "user-9",
		name: "Lewis Clarke",
		initials: "LC",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "4531 W Saile Dr, Batavia, North Dakota, 14020, United States",
		signedUpAs: "valid",
		email: "lewis@site.so",
		phone: undefined,
	},
	{
		id: "user-10",
		name: "Lori Hunter",
		initials: "LH",
		address: "2126 N Eagle Rd #120, Meridian, Illinois, 83646, United States",
		signedUpAs: "valid",
		email: "lori@site.so",
		phone: undefined,
	},
	{
		id: "user-11",
		name: "David Harrison",
		initials: "DH",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "3817 Beryl Rd, Raleigh, Nebraska, 27607, United States",
		signedUpAs: "valid",
		email: "david@site.so",
		phone: "+492-00-11",
	},
	{
		id: "user-12",
		name: "Chris Mathew",
		initials: "CM",
		address: "4807 3rd Ave, Kearney, New Hampshire, 68845, United States",
		signedUpAs: "fake",
		email: "chris@site.so",
		phone: "+234-95-86",
	},
	{
		id: "user-13",
		name: "Sophia Turner",
		initials: "ST",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "712 Walnut St, Philadelphia, PA 19106, United States",
		signedUpAs: "valid",
		email: "sophia@site.so",
		phone: "+1 415-555-01",
	},
	{
		id: "user-14",
		name: "Mason Vance",
		initials: "MV",
		address: "1004 Elm Street, Dallas, TX 75202, United States",
		signedUpAs: "valid",
		email: "mason@site.so",
		phone: undefined,
	},
	{
		id: "user-15",
		name: "Chloe Bennett",
		initials: "CB",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "550 Market St, San Francisco, CA 94104, United States",
		signedUpAs: "valid",
		email: "chloe@site.so",
		phone: "+1 650-321-44",
	},
	{
		id: "user-16",
		name: "Oliver Wright",
		initials: "OW",
		address: "88 Pine St, New York, NY 10005, United States",
		signedUpAs: "fake",
		email: "oliver@site.so",
		phone: "+44 20-7946",
	},
	{
		id: "user-17",
		name: "Emma Watson",
		initials: "EW",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "320 Congress Ave, Austin, TX 78701, United States",
		signedUpAs: "valid",
		email: "emma@site.so",
		phone: undefined,
	},
	{
		id: "user-18",
		name: "Lucas Grey",
		initials: "LG",
		address: "1400 16th St, Denver, CO 80202, United States",
		signedUpAs: "valid",
		email: "lucas@site.so",
		phone: "+1 303-888-21",
	},
	{
		id: "user-19",
		name: "Zoe Martinez",
		initials: "ZM",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "200 S Biscayne Blvd, Miami, FL 33131, United States",
		signedUpAs: "valid",
		email: "zoe@site.so",
		phone: "+1 305-999-12",
	},
	{
		id: "user-20",
		name: "Daniel Craig",
		initials: "DC",
		address: "500 Pike St, Seattle, WA 98101, United States",
		signedUpAs: "fake",
		email: "daniel@site.so",
		phone: undefined,
	},
	{
		id: "user-21",
		name: "Grace Hopper",
		initials: "GH",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "1 Kendall Sq, Cambridge, MA 02139, United States",
		signedUpAs: "valid",
		email: "grace@site.so",
		phone: "+1 617-555-88",
	},
	{
		id: "user-22",
		name: "Ethan Hunt",
		initials: "EH",
		address: "999 Canada Pl, Vancouver, BC V6C 3E1, Canada",
		signedUpAs: "valid",
		email: "ethan@site.so",
		phone: undefined,
	},
	{
		id: "user-23",
		name: "Mia Lin",
		initials: "ML",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "300 George St, Brisbane QLD 4000, Australia",
		signedUpAs: "valid",
		email: "mia@site.so",
		phone: "+61 7-3000-11",
	},
	{
		id: "user-24",
		name: "Benjamin Foster",
		initials: "BF",
		address: "70 King St W, Toronto, ON M5H 4B6, Canada",
		signedUpAs: "fake",
		email: "ben@site.so",
		phone: "+1 416-555-90",
	},
	{
		id: "user-25",
		name: "Ava Scott",
		initials: "AS",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "100 Liverpool St, London EC2M 2AT, United Kingdom",
		signedUpAs: "valid",
		email: "ava@site.so",
		phone: "+44 20-7123",
	},
	{
		id: "user-26",
		name: "Noah Taylor",
		initials: "NT",
		address: "250 Michigan Ave, Chicago, IL 60601, United States",
		signedUpAs: "fake",
		email: "noah@site.so",
		phone: undefined,
	},
	{
		id: "user-27",
		name: "Harper Lee",
		initials: "HL",
		avatarUrl: "/sandbox/placeholder.svg",
		address: "400 Capitol Mall, Sacramento, CA 95814, United States",
		signedUpAs: "valid",
		email: "harper@site.so",
		phone: "+1 916-555-77",
	},
]
