export interface ProjectAssignee {
	id: string
	name?: string
	initials?: string
	avatarUrl?: string
}

export interface ProjectItem {
	id: string
	name: string
	category: string
	tags: string[]
	assignees: ProjectAssignee[]
	progressStep: number
	progressTotal: number
	deadline?: string
	rating: number
}

export const PROJECTS_DATA: ProjectItem[] = [
	{
		id: "proj-1",
		name: "Improve website UI",
		category: "Website",
		tags: ["SaaS", "IT", "Tech", "B2B"],
		assignees: [
			{ id: "a1", avatarUrl: "/sandbox/placeholder.svg", initials: "AH" },
			{ id: "a2", avatarUrl: "/sandbox/placeholder.svg", initials: "RD" },
			{ id: "a3", initials: "L" },
			{ id: "a4", initials: "O" },
		],
		progressStep: 1,
		progressTotal: 5,
		deadline: "Apr 10, 2023",
		rating: 5,
	},
	{
		id: "proj-2",
		name: "Internal UX audit",
		category: "Website",
		tags: ["Ecommerce", "Shopify"],
		assignees: [
			{ id: "a5", avatarUrl: "/sandbox/placeholder.svg", initials: "CQ" },
			{ id: "a6", initials: "L" },
		],
		progressStep: 1,
		progressTotal: 5,
		deadline: "May 5, 2023",
		rating: 4,
	},
	{
		id: "proj-3",
		name: "Digital marketing",
		category: "IT department",
		tags: ["Sales", "Marketing"],
		assignees: [
			{ id: "a7", initials: "A" },
			{ id: "a8", initials: "B" },
			{ id: "a9", initials: "M" },
			{ id: "a10", initials: "C" },
			{ id: "a11", initials: "A" },
			{ id: "a12", initials: "E" },
		],
		progressStep: 5,
		progressTotal: 5,
		deadline: "Apr 29, 2023",
		rating: 5,
	},
	{
		id: "proj-4",
		name: "Case studies",
		category: "IT department",
		tags: ["Branding"],
		assignees: [
			{ id: "a13", avatarUrl: "/sandbox/placeholder.svg", initials: "AR" },
		],
		progressStep: 5,
		progressTotal: 5,
		deadline: undefined,
		rating: 3,
	},
	{
		id: "proj-5",
		name: "Social media assets",
		category: "Marketing",
		tags: ["B2B"],
		assignees: [
			{ id: "a14", initials: "A" },
			{ id: "a15", initials: "C" },
			{ id: "a16", avatarUrl: "/sandbox/placeholder.svg", initials: "BD" },
			{ id: "a17", initials: "M" },
		],
		progressStep: 0,
		progressTotal: 5,
		deadline: "Mar 16, 2023",
		rating: 2,
	},
	{
		id: "proj-6",
		name: "UI/UX library",
		category: "Marketing",
		tags: ["SaaS", "B2B"],
		assignees: [
			{ id: "a18", avatarUrl: "/sandbox/placeholder.svg", initials: "MC" },
			{ id: "a19", avatarUrl: "/sandbox/placeholder.svg", initials: "FH" },
			{ id: "a20", avatarUrl: "/sandbox/placeholder.svg", initials: "EL" },
		],
		progressStep: 2,
		progressTotal: 5,
		deadline: "Jun 1, 2023",
		rating: 4,
	},
	{
		id: "proj-7",
		name: "Defining core values of the Guideline",
		category: "Marketing",
		tags: ["Sales", "Branding"],
		assignees: [
			{ id: "a21", avatarUrl: "/sandbox/placeholder.svg", initials: "LC" },
			{ id: "a22", initials: "L" },
			{ id: "a23", initials: "O" },
		],
		progressStep: 5,
		progressTotal: 5,
		deadline: undefined,
		rating: 5,
	},
	{
		id: "proj-8",
		name: "Seeking feedback",
		category: "Company",
		tags: ["Tech", "IT", "Fintech", "AI"],
		assignees: [
			{ id: "a24", avatarUrl: "/sandbox/placeholder.svg", initials: "LH" },
			{ id: "a25", initials: "L" },
			{ id: "a26", avatarUrl: "/sandbox/placeholder.svg", initials: "DH" },
		],
		progressStep: 0,
		progressTotal: 5,
		deadline: "Apr 8, 2023",
		rating: 2,
	},
	{
		id: "proj-9",
		name: "Trending NFT Collections",
		category: "Analysis",
		tags: ["Crypto", "Wallet"],
		assignees: [
			{ id: "a27", avatarUrl: "/sandbox/placeholder.svg", initials: "CM" },
			{ id: "a28", initials: "L" },
			{ id: "a29", initials: "A" },
			{ id: "a30", avatarUrl: "/sandbox/placeholder.svg", initials: "ST" },
			{ id: "a31", initials: "O" },
		],
		progressStep: 4,
		progressTotal: 5,
		deadline: undefined,
		rating: 4,
	},
	{
		id: "proj-10",
		name: "Understanding and leveraging Notion strength",
		category: "Analysis",
		tags: ["Online"],
		assignees: [
			{ id: "a32", initials: "L" },
			{ id: "a33", initials: "O" },
		],
		progressStep: 4,
		progressTotal: 5,
		deadline: "Apr 25, 2023",
		rating: 3,
	},
	{
		id: "proj-11",
		name: "App design",
		category: "Branding",
		tags: ["Branding", "Design"],
		assignees: [
			{ id: "a34", avatarUrl: "/sandbox/placeholder.svg", initials: "MV" },
			{ id: "a35", initials: "L" },
			{ id: "a36", avatarUrl: "/sandbox/placeholder.svg", initials: "CB" },
		],
		progressStep: 2,
		progressTotal: 5,
		deadline: "Mar 3, 2023",
		rating: 5,
	},
	{
		id: "proj-12",
		name: "Untitled",
		category: "Not defined",
		tags: ["IT", "Tech", "B2B"],
		assignees: [
			{ id: "a37", avatarUrl: "/sandbox/placeholder.svg", initials: "OW" },
			{ id: "a38", initials: "L" },
			{ id: "a39", avatarUrl: "/sandbox/placeholder.svg", initials: "EW" },
		],
		progressStep: 0,
		progressTotal: 5,
		deadline: "May 22, 2023",
		rating: 1,
	},
	{
		id: "proj-13",
		name: "Design system migration",
		category: "Website",
		tags: ["SaaS", "Design"],
		assignees: [
			{ id: "a40", avatarUrl: "/sandbox/placeholder.svg", initials: "LG" },
			{ id: "a41", initials: "M" },
		],
		progressStep: 3,
		progressTotal: 5,
		deadline: "Jul 14, 2023",
		rating: 4,
	},
	{
		id: "proj-14",
		name: "Payment gateway integration",
		category: "Fintech",
		tags: ["Fintech", "Security"],
		assignees: [
			{ id: "a42", avatarUrl: "/sandbox/placeholder.svg", initials: "ZM" },
			{ id: "a43", initials: "T" },
			{ id: "a44", initials: "P" },
		],
		progressStep: 4,
		progressTotal: 5,
		deadline: "Aug 20, 2023",
		rating: 5,
	},
	{
		id: "proj-15",
		name: "User onboarding tour revamp",
		category: "Product",
		tags: ["UX", "Growth"],
		assignees: [
			{ id: "a45", avatarUrl: "/sandbox/placeholder.svg", initials: "DC" },
			{ id: "a46", initials: "L" },
		],
		progressStep: 2,
		progressTotal: 5,
		deadline: "Sep 2, 2023",
		rating: 4,
	},
	{
		id: "proj-16",
		name: "API rate limiting architecture",
		category: "Engineering",
		tags: ["Tech", "Infrastructure"],
		assignees: [
			{ id: "a47", avatarUrl: "/sandbox/placeholder.svg", initials: "GH" },
			{ id: "a48", initials: "E" },
		],
		progressStep: 5,
		progressTotal: 5,
		deadline: "Oct 11, 2023",
		rating: 5,
	},
	{
		id: "proj-17",
		name: "Annual security compliance review",
		category: "Security",
		tags: ["IT", "Compliance"],
		assignees: [
			{ id: "a49", avatarUrl: "/sandbox/placeholder.svg", initials: "EH" },
			{ id: "a50", initials: "S" },
		],
		progressStep: 3,
		progressTotal: 5,
		deadline: "Nov 30, 2023",
		rating: 4,
	},
	{
		id: "proj-18",
		name: "Mobile app dark mode rollout",
		category: "Mobile",
		tags: ["Design", "UI"],
		assignees: [
			{ id: "a51", avatarUrl: "/sandbox/placeholder.svg", initials: "ML" },
			{ id: "a52", initials: "K" },
		],
		progressStep: 4,
		progressTotal: 5,
		deadline: "Dec 18, 2023",
		rating: 5,
	},
	{
		id: "proj-19",
		name: "Customer support AI chatbot",
		category: "Support",
		tags: ["AI", "Tech"],
		assignees: [
			{ id: "a53", avatarUrl: "/sandbox/placeholder.svg", initials: "BF" },
			{ id: "a54", initials: "A" },
			{ id: "a55", initials: "I" },
		],
		progressStep: 1,
		progressTotal: 5,
		deadline: "Jan 15, 2024",
		rating: 3,
	},
	{
		id: "proj-20",
		name: "Quarterly churn rate analysis",
		category: "Analytics",
		tags: ["Data", "Analysis"],
		assignees: [
			{ id: "a56", avatarUrl: "/sandbox/placeholder.svg", initials: "AS" },
			{ id: "a57", initials: "Q" },
		],
		progressStep: 5,
		progressTotal: 5,
		deadline: "Feb 28, 2024",
		rating: 5,
	},
	{
		id: "proj-21",
		name: "Email marketing automation flow",
		category: "Marketing",
		tags: ["Marketing", "Sales"],
		assignees: [
			{ id: "a58", avatarUrl: "/sandbox/placeholder.svg", initials: "NT" },
			{ id: "a59", initials: "M" },
		],
		progressStep: 2,
		progressTotal: 5,
		deadline: "Mar 12, 2024",
		rating: 4,
	},
	{
		id: "proj-22",
		name: "Database query performance indexing",
		category: "Engineering",
		tags: ["Tech", "Database"],
		assignees: [
			{ id: "a60", avatarUrl: "/sandbox/placeholder.svg", initials: "HL" },
			{ id: "a61", initials: "D" },
		],
		progressStep: 4,
		progressTotal: 5,
		deadline: "Apr 5, 2024",
		rating: 4,
	},
	{
		id: "proj-23",
		name: "Brand identity guidelines refresh",
		category: "Branding",
		tags: ["Branding", "Creative"],
		assignees: [
			{ id: "a62", avatarUrl: "/sandbox/placeholder.svg", initials: "SL" },
			{ id: "a63", initials: "B" },
		],
		progressStep: 1,
		progressTotal: 5,
		deadline: "May 19, 2024",
		rating: 3,
	},
	{
		id: "proj-24",
		name: "Multi-tenant tenant isolation",
		category: "Infrastructure",
		tags: ["Cloud", "Security"],
		assignees: [
			{ id: "a64", avatarUrl: "/sandbox/placeholder.svg", initials: "JK" },
			{ id: "a65", initials: "N" },
		],
		progressStep: 5,
		progressTotal: 5,
		deadline: "Jun 22, 2024",
		rating: 5,
	},
	{
		id: "proj-25",
		name: "Public API documentation portal",
		category: "Documentation",
		tags: ["Developer", "Docs"],
		assignees: [
			{ id: "a66", avatarUrl: "/sandbox/placeholder.svg", initials: "PA" },
			{ id: "a67", initials: "P" },
		],
		progressStep: 3,
		progressTotal: 5,
		deadline: "Jul 8, 2024",
		rating: 4,
	},
	{
		id: "proj-26",
		name: "Social login provider additions",
		category: "Authentication",
		tags: ["Auth", "Security"],
		assignees: [
			{ id: "a68", avatarUrl: "/sandbox/placeholder.svg", initials: "RF" },
			{ id: "a69", initials: "O" },
		],
		progressStep: 4,
		progressTotal: 5,
		deadline: "Aug 15, 2024",
		rating: 5,
	},
	{
		id: "proj-27",
		name: "Internationalization and localization",
		category: "Product",
		tags: ["Global", "i18n"],
		assignees: [
			{ id: "a70", avatarUrl: "/sandbox/placeholder.svg", initials: "AM" },
			{ id: "a71", initials: "G" },
		],
		progressStep: 2,
		progressTotal: 5,
		deadline: "Sep 28, 2024",
		rating: 4,
	},
]
