export const FLAG_CDN_ORIGIN = "https://cdn.jsdelivr.net"

const FLAG_CDN_ROOT =
	"https://cdn.jsdelivr.net/gh/Radian-os/radian-resources@main/packages/country-flags/src/64px"

export const flagNames = [
	"Abkhazia",
	"Afghanistan",
	"Alandislands",
	"Albania",
	"Algeria",
	"Americansamoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antiguaandbarbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Australia",
	"Austria",
	"Azerbaijan",
	"Azoresislands",
	"Bahamas",
	"Bahrain",
	"Balearicislands",
	"Bangladesh",
	"Barbados",
	"Basquecountry",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia",
	"Bonaire",
	"Bosniaandherzegovina",
	"Botswana",
	"Brazil",
	"Britishcolumbia",
	"Britishindianoceanterritory",
	"Britishvirginislands",
	"Brunei",
	"Bulgaria",
	"Burkinafaso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Canada",
	"Canaryislands",
	"Capeverde",
	"Caymanislands",
	"Centralafricanrepublic",
	"Ceuta",
	"Chad",
	"Chile",
	"China",
	"Christmasisland",
	"Cocosisland",
	"Colombia",
	"Comoros",
	"Cookisland",
	"Corsica",
	"Costarica",
	"Croatia",
	"Cuba",
	"Curacao",
	"Czechrepublic",
	"Democraticrepublicofcongo",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominicanrepublic",
	"Easttimor",
	"Ecuador",
	"Egypt",
	"Elsalvador",
	"England",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Europeanunion",
	"Falklandislands",
	"Fiji",
	"Finland",
	"France",
	"Frenchpolynesia",
	"Gabon",
	"Galapagosislands",
	"Gambia",
	"Georgia",
	"Germany",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guineabissau",
	"Haiti",
	"Hawaii",
	"Honduras",
	"Hongkong",
	"Hungary",
	"Iceland",
	"India",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Isleofman",
	"Israel",
	"Italy",
	"Ivorycoast",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Laos",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Madeira",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshallisland",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Melilla",
	"Mexico",
	"Micronesia",
	"Moldova",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nato",
	"Nauru",
	"Nepal",
	"Netherlands",
	"Newzealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolkisland",
	"Northerncyprus",
	"Northernmarianasislands",
	"Northkorea",
	"Norway",
	"Oman",
	"Ossetia",
	"Pakistan",
	"Palau",
	"Palestine",
	"Panama",
	"Papuanewguinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairnislands",
	"Poland",
	"Portugal",
	"Puertorico",
	"Qatar",
	"Rapanui",
	"Republicofmacedonia",
	"Republicofthecongo",
	"Romania",
	"Russia",
	"Rwanda",
	"Sabaisland",
	"Sahrawiarabdemocraticrepublic",
	"Saintkittsandnevis",
	"Samoa",
	"Sanmarino",
	"Saotomeandprince",
	"Sardinia",
	"Saudiarabia",
	"Scotland",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierraleone",
	"Singapore",
	"Sinteustatius",
	"Sintmaarten",
	"Slovakia",
	"Slovenia",
	"Somalia",
	"Somaliland",
	"Southafrica",
	"Southkorea",
	"Southsudan",
	"Spain",
	"Srilanka",
	"St Vincent And The Grenadines",
	"Stbarts",
	"Stlucia",
	"Sudan",
	"Suriname",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Tibet",
	"Togo",
	"Tokelau",
	"Tonga",
	"Transnistria",
	"Trinidadandtobago",
	"Tunisia",
	"Turkey",
	"Turkmenistan",
	"Turksandcaicos",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United States",
	"Unitedarabemirates",
	"Unitedkingdom",
	"Unitednations",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Vaticancity",
	"Venezuela",
	"Vietnam",
	"Virgin Islands",
	"Wales",
	"Yemen",
	"Zambia",
	"Zimbabwe",
] as const

export type FlagName = (typeof flagNames)[number]
export type FlagShape = "flat" | "round"

const flagDisplayNames: Partial<Record<FlagName, string>> = {
	Alandislands: "Åland Islands",
	Americansamoa: "American Samoa",
	Antiguaandbarbuda: "Antigua and Barbuda",
	Azoresislands: "Azores Islands",
	Balearicislands: "Balearic Islands",
	Basquecountry: "Basque Country",
	Bosniaandherzegovina: "Bosnia and Herzegovina",
	Britishcolumbia: "British Columbia",
	Britishindianoceanterritory: "British Indian Ocean Territory",
	Britishvirginislands: "British Virgin Islands",
	Burkinafaso: "Burkina Faso",
	Canaryislands: "Canary Islands",
	Capeverde: "Cape Verde",
	Caymanislands: "Cayman Islands",
	Centralafricanrepublic: "Central African Republic",
	Christmasisland: "Christmas Island",
	Cocosisland: "Cocos Islands",
	Cookisland: "Cook Islands",
	Costarica: "Costa Rica",
	Czechrepublic: "Czech Republic",
	Democraticrepublicofcongo: "Democratic Republic of the Congo",
	Dominicanrepublic: "Dominican Republic",
	Easttimor: "East Timor",
	Elsalvador: "El Salvador",
	Europeanunion: "European Union",
	Falklandislands: "Falkland Islands",
	Frenchpolynesia: "French Polynesia",
	Galapagosislands: "Galapagos Islands",
	Guineabissau: "Guinea-Bissau",
	Hongkong: "Hong Kong",
	Isleofman: "Isle of Man",
	Ivorycoast: "Ivory Coast",
	Marshallisland: "Marshall Islands",
	Nato: "NATO",
	Newzealand: "New Zealand",
	Norfolkisland: "Norfolk Island",
	Northerncyprus: "Northern Cyprus",
	Northernmarianasislands: "Northern Mariana Islands",
	Northkorea: "North Korea",
	Ossetia: "South Ossetia",
	Papuanewguinea: "Papua New Guinea",
	Pitcairnislands: "Pitcairn Islands",
	Puertorico: "Puerto Rico",
	Rapanui: "Rapa Nui",
	Republicofmacedonia: "Republic of Macedonia",
	Republicofthecongo: "Republic of the Congo",
	Sahrawiarabdemocraticrepublic: "Sahrawi Arab Democratic Republic",
	Saintkittsandnevis: "Saint Kitts and Nevis",
	Sanmarino: "San Marino",
	Saudiarabia: "Saudi Arabia",
	Sierraleone: "Sierra Leone",
	Sinteustatius: "Sint Eustatius",
	Sintmaarten: "Sint Maarten",
	Southafrica: "South Africa",
	Southkorea: "South Korea",
	Southsudan: "South Sudan",
	Srilanka: "Sri Lanka",
	"St Vincent And The Grenadines": "St. Vincent and the Grenadines",
	Stbarts: "St. Barts",
	Stlucia: "St. Lucia",
	Trinidadandtobago: "Trinidad and Tobago",
	Turksandcaicos: "Turks and Caicos Islands",
	Unitedarabemirates: "United Arab Emirates",
	Unitedkingdom: "United Kingdom",
	Unitednations: "United Nations",
	Vaticancity: "Vatican City",
}

export function getFlagDisplayName(name: FlagName) {
	return flagDisplayNames[name] ?? name
}

export function getFlagUrl(name: FlagName, shape: FlagShape = "flat") {
	const folder = shape === "round" ? "circle" : "flat"
	return `${FLAG_CDN_ROOT}/${folder}/${encodeURIComponent(name)}.png`
}

export function getFlagSvgMarkup(name: FlagName, imageHref: string) {
	return `<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 64 64" role="img" aria-label="${getFlagDisplayName(name)} flag"><image href="${imageHref}" width="64" height="64" /></svg>`
}

export function getFlagNextImageMarkup(
	name: FlagName,
	shape: FlagShape = "flat"
) {
	return `<Image src="${getFlagUrl(name, shape)}" alt="${getFlagDisplayName(name)} flag" width={48} height={48} />`
}

export function getFlagHtmlMarkup(name: FlagName, shape: FlagShape = "flat") {
	return `<img src="${getFlagUrl(name, shape)}" alt="${getFlagDisplayName(name)} flag" width="48" height="48" />`
}
