// @ts-nocheck
// This file is generated by scripts/generate-blocks-index.ts
// Do not edit this file manually
import * as React from "react"

export type RegistryItem = {
	name: string
	type: "block" | "components"
	files: {
		path: string
		name: string
		type: "page" | "components"
		target?: string
	}[]
	component: React.LazyExoticComponent<React.ComponentType<any>>
}

export const Index: Record<string, RegistryItem> = {
	"new-password": {
		name: "new-password",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\new-password\\components\\brand-logo.tsx",
				name: "brand-logo.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\new-password\\components\\new-password-form.tsx",
				name: "new-password-form.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\new-password\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/new-password/page")
		),
	},
	"preview-01": {
		name: "preview-01",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\preview-01\\common\\card-first.tsx",
				name: "card-first.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\preview-01\\common\\common-card.tsx",
				name: "common-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\preview-01\\common\\cookie-card.tsx",
				name: "cookie-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\preview-01\\common\\dropdown.tsx",
				name: "dropdown.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\preview-01\\common\\invite-card.tsx",
				name: "invite-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\preview-01\\common\\report-card.tsx",
				name: "report-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\preview-01\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/preview-01/page")
		),
	},
	"preview-02": {
		name: "preview-02",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\preview-02\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/preview-02/page")
		),
	},
	"preview-03": {
		name: "preview-03",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\preview-03\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/preview-03/page")
		),
	},
	"reset-email": {
		name: "reset-email",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\reset-email\\components\\brand-logo.tsx",
				name: "brand-logo.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\reset-email\\components\\gmail-icon.tsx",
				name: "gmail-icon.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\reset-email\\components\\mail-logo.tsx",
				name: "mail-logo.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\reset-email\\components\\reset-email.tsx",
				name: "reset-email.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\reset-email\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/reset-email/page")
		),
	},
	"sidebar-dark": {
		name: "sidebar-dark",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-dark\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-dark\\components\\info-card.tsx",
				name: "info-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-dark\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-dark\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-dark\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-dark/page")
		),
	},
	"sidebar-doc": {
		name: "sidebar-doc",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-doc\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-doc\\components\\info-card.tsx",
				name: "info-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-doc\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-doc\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-doc\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-doc/page")
		),
	},
	"sidebar-floating": {
		name: "sidebar-floating",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-floating\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-floating\\components\\info-card.tsx",
				name: "info-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-floating\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-floating\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-floating\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-floating/page")
		),
	},
	"sidebar-inset": {
		name: "sidebar-inset",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-inset\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-inset\\components\\info-card.tsx",
				name: "info-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-inset\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-inset\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-inset\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-inset/page")
		),
	},
	"sidebar-offcanvas": {
		name: "sidebar-offcanvas",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-offcanvas\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-offcanvas\\components\\info-card-expanded.tsx",
				name: "info-card-expanded.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-offcanvas\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-offcanvas\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-offcanvas\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-offcanvas/page")
		),
	},
	"sidebar-rail": {
		name: "sidebar-rail",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-rail\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-rail\\components\\info-card.tsx",
				name: "info-card.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-rail\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-rail\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-rail\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-rail/page")
		),
	},
	"sidebar-resize": {
		name: "sidebar-resize",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\sidebar-resize\\components\\app-sidebar.tsx",
				name: "app-sidebar.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-resize\\components\\info-card-expanded.tsx",
				name: "info-card-expanded.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-resize\\components\\logos.tsx",
				name: "logos.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-resize\\components\\sidebar-footer-user.tsx",
				name: "sidebar-footer-user.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\sidebar-resize\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/sidebar-resize/page")
		),
	},
	signin: {
		name: "signin",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\signin\\components\\brand-logo.tsx",
				name: "brand-logo.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signin\\components\\github-icon.tsx",
				name: "github-icon.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signin\\components\\google-icon.tsx",
				name: "google-icon.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signin\\components\\signin-form.tsx",
				name: "signin-form.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signin\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/signin/page")
		),
	},
	signup: {
		name: "signup",
		type: "block",
		files: [
			{
				path: "registry\\blocks-example\\signup\\components\\github-icon.tsx",
				name: "github-icon.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signup\\components\\google-icon.tsx",
				name: "google-icon.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signup\\components\\radian-logo.tsx",
				name: "radian-logo.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signup\\components\\signup-form.tsx",
				name: "signup-form.tsx",
				type: "components",
				target: "",
			},
			{
				path: "registry\\blocks-example\\signup\\page.tsx",
				name: "page.tsx",
				type: "page",
			},
		],
		component: React.lazy(
			() => import("@/registry/blocks-example/signup/page")
		),
	},
}
