export const RADIUS = [
	{
		value: "none",
		name: "None",
		type: "registry:radius",
		radius: {
			// xs: "0px",
			// sm: "0px",
			// md: "0px",
			// lg: "0px",
			// xl: "0px",
			// "2xl": "0px",
			// "3xl": "0px",
			// "4xl": "0px",
			"control-sm": "0px",
			control: "0px",
			"surface-sm": "0px",
			surface: "0px",
			pill: "999px",
			"element-sm": "0px",
			element: "0px",
			"element-lg": "0px",
		},
	},
	{
		value: "small",
		name: "Small",
		type: "registry:radius",
		radius: {
			// xs: "1px",
			// sm: "2px",
			// md: "4px",
			// lg: "4px",
			// xl: "6px",
			// "2xl": "8px",
			// "3xl": "10px",
			// "4xl": "12px",
		},
	},
	{
		value: "medium",
		name: "Medium",
		type: "registry:radius",
		radius: {
			// xs: "2px",
			// sm: "4px",
			// md: "6px",
			// lg: "8px",
			// xl: "12px",
			// "2xl": "16px",
			// "3xl": "20px",
			// "4xl": "24px",
		},
	},
	{
		value: "large",
		name: "Large",
		type: "registry:radius",
		radius: {
			// xs: "2px",
			// sm: "4px",
			// md: "8px",
			// lg: "12px",
			// xl: "20px",
			// "2xl": "28px",
			// "3xl": "36px",
			// "4xl": "48px",

			"control-sm": "999px",
			control: "999px",
			"surface-sm": "10px",
			surface: "14px",
			pill: "999px",
			"element-sm": "6px",
			element: "8px",
			"element-lg": "12px",
		},
	},
] as const

export type Radius = (typeof RADIUS)[number]
export type RadiusValue = Radius["value"]
