export const RADIUS = [
	{
		value: "none",
		name: "None",
		type: "registry:radius",
		radius: {
			// xs: "0px",
			// sm: "0px",
			// md: "0px",
			// lg: "0px",
			// xl: "0px",
			// "2xl": "0px",
			// "3xl": "0px",
			// "4xl": "0px",
			"control-md": "0px",
			"control-lg": "0px",
			"surface-md": "0px",
			"surface-lg": "0px",
			"surface-xl": "0px",
			"surface-2xl": "0px",
			"element-sm": "0px",
			"element-md": "0px",
			"element-lg": "0px",
			"element-xl": "0px",
			"element-2xl": "0px",
		},
	},
	{
		value: "small",
		name: "Small",
		type: "registry:radius",
		radius: {
			// xs: "1px",
			// sm: "2px",
			// md: "4px",
			// lg: "4px",
			// xl: "6px",
			// "2xl": "8px",
			// "3xl": "10px",
			// "4xl": "12px",
			"control-md": "4px",
			"control-lg": "6px",
			"surface-md": "4px",
			"surface-lg": "6px",
			"surface-xl": "8px",
			"surface-2xl": "12px",
			"element-sm": "1px",
			"element-md": "2px",
			"element-lg": "4px",
			"element-xl": "8px",
			"element-2xl": "12px",
		},
	},
	{
		value: "medium",
		name: "Medium",
		type: "registry:radius",
		radius: {
			// xs: "2px",
			// sm: "4px",
			// md: "6px",
			// lg: "8px",
			// xl: "12px",
			// "2xl": "16px",
			// "3xl": "20px",
			// "4xl": "24px",
			"control-md": "6px",
			"control-lg": "8px",
			"surface-md": "6px",
			"surface-lg": "8px",
			"surface-xl": "12px",
			"surface-2xl": "16px",
			"element-sm": "2px",
			"element-md": "4px",
			"element-lg": "8px",
			"element-xl": "12px",
			"element-2xl": "16px",
		},
	},
	{
		value: "large",
		name: "Large",
		type: "registry:radius",
		radius: {
			// xs: "2px",
			// sm: "4px",
			// md: "8px",
			// lg: "12px",
			// xl: "20px",
			// "2xl": "28px",
			// "3xl": "36px",
			// "4xl": "48px",
			"control-md": "9999px",
			"control-lg": "9999px",
			"surface-md": "8px",
			"surface-lg": "12px",
			"surface-xl": "16px",
			"surface-2xl": "20px",
			"element-sm": "4px",
			"element-md": "8px",
			"element-lg": "12px",
			"element-xl": "16px",
			"element-2xl": "20px",
		},
	},
] as const

export type Radius = (typeof RADIUS)[number]
export type RadiusValue = Radius["value"]
