// This file is autogenerated by scripts/build-registry-map.ts
// Do not edit this file directly.
import * as React from "react"

const registry: Record<
	string,
	React.LazyExoticComponent<React.ComponentType>
> = {
	"accordion-indicator": React.lazy(
		() => import("@/registry/example/accordion/accordion-indicator")
	),
	"accordion-large": React.lazy(
		() => import("@/registry/example/accordion/accordion-large")
	),
	"accordion-nested": React.lazy(
		() => import("@/registry/example/accordion/accordion-nested")
	),
	"accordion-open": React.lazy(
		() => import("@/registry/example/accordion/accordion-open")
	),
	"accordion-preview": React.lazy(
		() => import("@/registry/example/accordion/accordion-preview")
	),
	"accordion-small": React.lazy(
		() => import("@/registry/example/accordion/accordion-small")
	),
	"accordion-table": React.lazy(
		() => import("@/registry/example/accordion/accordion-table")
	),
	"accordion-with-chevron-left": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-chevron-left")
	),
	"accordion-with-icon": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-icon")
	),
	"accordion-with-sub-header": React.lazy(
		() => import("@/registry/example/accordion/accordion-with-sub-header")
	),
	"alert-close-example-preview": React.lazy(
		() => import("@/registry/example/alert/alert-close-example-preview")
	),
	"alert-colors-example": React.lazy(
		() => import("@/registry/example/alert/alert-colors-example")
	),
	"alert-error-examples": React.lazy(
		() => import("@/registry/example/alert/alert-error-examples")
	),
	"alert-info-examples": React.lazy(
		() => import("@/registry/example/alert/alert-info-examples")
	),
	"alert-preview": React.lazy(
		() => import("@/registry/example/alert/alert-preview")
	),
	"alert-success-examples": React.lazy(
		() => import("@/registry/example/alert/alert-success-examples")
	),
	"alert-variants-example": React.lazy(
		() => import("@/registry/example/alert/alert-variants-example")
	),
	"alert-warning-example": React.lazy(
		() => import("@/registry/example/alert/alert-warning-example")
	),
	"alert-dialog-preview": React.lazy(
		() => import("@/registry/example/alert-dialog/alert-dialog-preview")
	),
	"backdrop-blur": React.lazy(
		() => import("@/registry/example/alert-dialog/backdrop-blur")
	),
	"backdrop-transparent": React.lazy(
		() => import("@/registry/example/alert-dialog/backdrop-transparent")
	),
	"destructive-alert-dialog": React.lazy(
		() => import("@/registry/example/alert-dialog/destructive-alert-dialog")
	),
	"destructive-dialog-center": React.lazy(
		() => import("@/registry/example/alert-dialog/destructive-dialog-center")
	),
	"destructive-dialog-with-divider": React.lazy(
		() =>
			import("@/registry/example/alert-dialog/destructive-dialog-with-divider")
	),
	"aspect-ratio-1-1": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-1-1")
	),
	"aspect-ratio-4-3": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-4-3")
	),
	"aspect-ratio-9-16": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-9-16")
	),
	"aspect-ratio-preview-16-9": React.lazy(
		() => import("@/registry/example/aspect-ratio/aspect-ratio-preview-16-9")
	),
	"account-verified": React.lazy(
		() => import("@/registry/example/auth-blocks/account-verified")
	),
	"email-code": React.lazy(
		() => import("@/registry/example/auth-blocks/email-code")
	),
	"email-verofy": React.lazy(
		() => import("@/registry/example/auth-blocks/email-verofy")
	),
	signin: React.lazy(() => import("@/registry/example/auth-blocks/signin")),
	signup: React.lazy(() => import("@/registry/example/auth-blocks/signup")),
	"avatar-fallback": React.lazy(
		() => import("@/registry/example/avatar/avatar-fallback")
	),
	"avatar-group": React.lazy(
		() => import("@/registry/example/avatar/avatar-group")
	),
	"avatar-preview": React.lazy(
		() => import("@/registry/example/avatar/avatar-preview")
	),
	"avatar-rounded-square": React.lazy(
		() => import("@/registry/example/avatar/avatar-rounded-square")
	),
	"avatar-size": React.lazy(
		() => import("@/registry/example/avatar/avatar-size")
	),
	"avatar-status": React.lazy(
		() => import("@/registry/example/avatar/avatar-status")
	),
	"custom-avatar-with-badge": React.lazy(
		() => import("@/registry/example/avatar/custom-avatar-with-badge")
	),
	"custom-avatar-with-ring": React.lazy(
		() => import("@/registry/example/avatar/custom-avatar-with-ring")
	),
	"custom-avatar-with-status": React.lazy(
		() => import("@/registry/example/avatar/custom-avatar-with-status")
	),
	"badge-avatar-example": React.lazy(
		() => import("@/registry/example/badge/badge-avatar-example")
	),
	"badge-color-example": React.lazy(
		() => import("@/registry/example/badge/badge-color-example")
	),
	"badge-cross-example": React.lazy(
		() => import("@/registry/example/badge/badge-cross-example")
	),
	"badge-dot-example": React.lazy(
		() => import("@/registry/example/badge/badge-dot-example")
	),
	"badge-example": React.lazy(
		() => import("@/registry/example/badge/badge-example")
	),
	"badge-icon-example": React.lazy(
		() => import("@/registry/example/badge/badge-icon-example")
	),
	"badge-nested-example": React.lazy(
		() => import("@/registry/example/badge/badge-nested-example")
	),
	"badge-rounded-example": React.lazy(
		() => import("@/registry/example/badge/badge-rounded-example")
	),
	"badge-size-example": React.lazy(
		() => import("@/registry/example/badge/badge-size-example")
	),
	"badge-variants-example": React.lazy(
		() => import("@/registry/example/badge/badge-variants-example")
	),
	"banner-black-friday-example": React.lazy(
		() => import("@/registry/example/banner/banner-black-friday-example")
	),
	"banner-color-example": React.lazy(
		() => import("@/registry/example/banner/banner-color-example")
	),
	"banner-error-example": React.lazy(
		() => import("@/registry/example/banner/banner-error-example")
	),
	"banner-example-preview": React.lazy(
		() => import("@/registry/example/banner/banner-example-preview")
	),
	"banner-floating-example": React.lazy(
		() => import("@/registry/example/banner/banner-floating-example")
	),
	"banner-primary-example": React.lazy(
		() => import("@/registry/example/banner/banner-primary-example")
	),
	"banner-success-example": React.lazy(
		() => import("@/registry/example/banner/banner-success-example")
	),
	"banner-variants-example": React.lazy(
		() => import("@/registry/example/banner/banner-variants-example")
	),
	"breadcrumb-card-design": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-card-design")
	),
	"breadcrumb-preview": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-preview")
	),
	"breadcrumb-with-dot": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-dot")
	),
	"breadcrumb-with-dropdown": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-dropdown")
	),
	"breadcrumb-with-icons": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-icons")
	),
	"breadcrumb-with-slash": React.lazy(
		() => import("@/registry/example/breadcrumb/breadcrumb-with-slash")
	),
	"button-colors-example": React.lazy(
		() => import("@/registry/example/button/button-colors-example")
	),
	"button-elevated-example": React.lazy(
		() => import("@/registry/example/button/button-elevated-example")
	),
	"button-example-disabled": React.lazy(
		() => import("@/registry/example/button/button-example-disabled")
	),
	"button-example-preview": React.lazy(
		() => import("@/registry/example/button/button-example-preview")
	),
	"button-example-rounded": React.lazy(
		() => import("@/registry/example/button/button-example-rounded")
	),
	"button-fancy-example": React.lazy(
		() => import("@/registry/example/button/button-fancy-example")
	),
	"button-fancy-preview": React.lazy(
		() => import("@/registry/example/button/button-fancy-preview")
	),
	"button-glossy-example": React.lazy(
		() => import("@/registry/example/button/button-glossy-example")
	),
	"button-group-example": React.lazy(
		() => import("@/registry/example/button/button-group-example")
	),
	"button-input-example": React.lazy(
		() => import("@/registry/example/button/button-input-example")
	),
	"button-size-example": React.lazy(
		() => import("@/registry/example/button/button-size-example")
	),
	"button-smooth-example": React.lazy(
		() => import("@/registry/example/button/button-smooth-example")
	),
	"button-split-example": React.lazy(
		() => import("@/registry/example/button/button-split-example")
	),
	"button-variants-example": React.lazy(
		() => import("@/registry/example/button/button-variants-example")
	),
	"button-with-badge-example": React.lazy(
		() => import("@/registry/example/button/button-with-badge-example")
	),
	"button-with-icon-example": React.lazy(
		() => import("@/registry/example/button/button-with-icon-example")
	),
	"compact-button-example": React.lazy(
		() => import("@/registry/example/button/compact-button-example")
	),
	"icon-button-example": React.lazy(
		() => import("@/registry/example/button/icon-button-example")
	),
	"link-button-example": React.lazy(
		() => import("@/registry/example/button/link-button-example")
	),
	"loading-button-example": React.lazy(
		() => import("@/registry/example/button/loading-button-example")
	),
	"social-button-example": React.lazy(
		() => import("@/registry/example/button/social-button-example")
	),
	"svg-button-example": React.lazy(
		() => import("@/registry/example/button/svg-button-example")
	),
	"calendar-footer-preview": React.lazy(
		() => import("@/registry/example/calendar/calendar-footer-preview")
	),
	"calendar-preview": React.lazy(
		() => import("@/registry/example/calendar/calendar-preview")
	),
	"calendar-scrollable-time": React.lazy(
		() => import("@/registry/example/calendar/calendar-scrollable-time")
	),
	"calendar-time-input": React.lazy(
		() => import("@/registry/example/calendar/calendar-time-input")
	),
	"calendar-year-month-selector-example": React.lazy(
		() =>
			import("@/registry/example/calendar/calendar-year-month-selector-example")
	),
	"multiple-months-calendar-example": React.lazy(
		() => import("@/registry/example/calendar/multiple-months-calendar-example")
	),
	"quick-selection-preview": React.lazy(
		() => import("@/registry/example/calendar/quick-selection-preview")
	),
	"time-picker-calendar-preview": React.lazy(
		() => import("@/registry/example/calendar/time-picker-calendar-preview")
	),
	"card-info-example": React.lazy(
		() => import("@/registry/example/card/card-info-example")
	),
	"card-preview": React.lazy(
		() => import("@/registry/example/card/card-preview")
	),
	"card-with-list-example": React.lazy(
		() => import("@/registry/example/card/card-with-list-example")
	),
	"carousel-autoplay": React.lazy(
		() => import("@/registry/example/carousel/carousel-autoplay")
	),
	"carousel-dotbutton": React.lazy(
		() => import("@/registry/example/carousel/carousel-dotbutton")
	),
	"carousel-loop": React.lazy(
		() => import("@/registry/example/carousel/carousel-loop")
	),
	"carousel-orientation": React.lazy(
		() => import("@/registry/example/carousel/carousel-orientation")
	),
	"carousel-preview": React.lazy(
		() => import("@/registry/example/carousel/carousel-preview")
	),
	"carousel-scale": React.lazy(
		() => import("@/registry/example/carousel/carousel-scale")
	),
	"carousel-size": React.lazy(
		() => import("@/registry/example/carousel/carousel-size")
	),
	"carousel-space": React.lazy(
		() => import("@/registry/example/carousel/carousel-space")
	),
	"checkbox-card": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-card")
	),
	"checkbox-checked": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-checked")
	),
	"checkbox-disabled": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-disabled")
	),
	"checkbox-form": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-form")
	),
	"checkbox-group": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-group")
	),
	"checkbox-preview": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-preview")
	),
	"checkbox-size": React.lazy(
		() => import("@/registry/example/checkbox/checkbox-size")
	),
	"indeterminate-checkbox": React.lazy(
		() => import("@/registry/example/checkbox/indeterminate-checkbox")
	),
	"code-area-preview": React.lazy(
		() => import("@/registry/example/code-area/code-area-preview")
	),
	"code-language-example": React.lazy(
		() => import("@/registry/example/code-area/code-language-example")
	),
	"code-theme-example": React.lazy(
		() => import("@/registry/example/code-area/code-theme-example")
	),
	"code-with-copy-example": React.lazy(
		() => import("@/registry/example/code-area/code-with-copy-example")
	),
	"code-with-tabs-preview": React.lazy(
		() => import("@/registry/example/code-area/code-with-tabs-preview")
	),
	"collapsible-form": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-form")
	),
	"collapsible-menu": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-menu")
	),
	"collapsible-preview": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-preview")
	),
	"collapsible-text": React.lazy(
		() => import("@/registry/example/collapsible/collapsible-text")
	),
	"combobox-email-invite": React.lazy(
		() => import("@/registry/example/combobox/combobox-email-invite")
	),
	"combobox-form": React.lazy(
		() => import("@/registry/example/combobox/combobox-form")
	),
	"combobox-multiselect": React.lazy(
		() => import("@/registry/example/combobox/combobox-multiselect")
	),
	"combobox-preview": React.lazy(
		() => import("@/registry/example/combobox/combobox-preview")
	),
	"combobox-scrollarea": React.lazy(
		() => import("@/registry/example/combobox/combobox-scrollarea")
	),
	"combobox-timezone": React.lazy(
		() => import("@/registry/example/combobox/combobox-timezone")
	),
	"virtualized-list": React.lazy(
		() => import("@/registry/example/combobox/virtualized-list")
	),
	"command-preview": React.lazy(
		() => import("@/registry/example/command/command-preview")
	),
	"currency-decimal-separator": React.lazy(
		() => import("@/registry/example/currency-input/currency-decimal-separator")
	),
	"currency-decimals-limit": React.lazy(
		() => import("@/registry/example/currency-input/currency-decimals-limit")
	),
	"currency-input-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-input-example")
	),
	"currency-locale-config": React.lazy(
		() => import("@/registry/example/currency-input/currency-locale-config")
	),
	"currency-max-value-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-max-value-example")
	),
	"currency-nodecimal-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-nodecimal-example")
	),
	"currency-prefix-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-prefix-example")
	),
	"currency-select-with-custom-prefix": React.lazy(
		() =>
			import(
				"@/registry/example/currency-input/currency-select-with-custom-prefix"
			)
	),
	"currency-separators-example": React.lazy(
		() =>
			import("@/registry/example/currency-input/currency-separators-example")
	),
	"currency-step-example": React.lazy(
		() => import("@/registry/example/currency-input/currency-step-example")
	),
	"currency-with-input-group": React.lazy(
		() => import("@/registry/example/currency-input/currency-with-input-group")
	),
	"currency-with-input-wrapper": React.lazy(
		() =>
			import("@/registry/example/currency-input/currency-with-input-wrapper")
	),
	"currency-with-prefix": React.lazy(
		() => import("@/registry/example/currency-input/currency-with-prefix")
	),
	"date-picker-form": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-form")
	),
	"date-picker-preview": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-preview")
	),
	"date-picker-range-example": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-range-example")
	),
	"date-picker-with-time": React.lazy(
		() => import("@/registry/example/date-picker/date-picker-with-time")
	),
	"dialog-backdrop-blur": React.lazy(
		() => import("@/registry/example/dialog/dialog-backdrop-blur")
	),
	"dialog-backdrop-transparent": React.lazy(
		() => import("@/registry/example/dialog/dialog-backdrop-transparent")
	),
	"dialog-close-button-hidden": React.lazy(
		() => import("@/registry/example/dialog/dialog-close-button-hidden")
	),
	"dialog-close-button-hover": React.lazy(
		() => import("@/registry/example/dialog/dialog-close-button-hover")
	),
	"dialog-destructive": React.lazy(
		() => import("@/registry/example/dialog/dialog-destructive")
	),
	"dialog-preview": React.lazy(
		() => import("@/registry/example/dialog/dialog-preview")
	),
	"dialog-with-form": React.lazy(
		() => import("@/registry/example/dialog/dialog-with-form")
	),
	"divider-badge-preview": React.lazy(
		() => import("@/registry/example/divider/divider-badge-preview")
	),
	"divider-plain-text-preview": React.lazy(
		() => import("@/registry/example/divider/divider-plain-text-preview")
	),
	"divider-preview": React.lazy(
		() => import("@/registry/example/divider/divider-preview")
	),
	"divider-text-preview": React.lazy(
		() => import("@/registry/example/divider/divider-text-preview")
	),
	"drawer-backdrop-example": React.lazy(
		() => import("@/registry/example/drawer/drawer-backdrop-example")
	),
	"drawer-example-preview": React.lazy(
		() => import("@/registry/example/drawer/drawer-example-preview")
	),
	"drawer-handle-preview": React.lazy(
		() => import("@/registry/example/drawer/drawer-handle-preview")
	),
	"drawer-position-example": React.lazy(
		() => import("@/registry/example/drawer/drawer-position-example")
	),
	"drawer-variant-example": React.lazy(
		() => import("@/registry/example/drawer/drawer-variant-example")
	),
	"dropdown-preview": React.lazy(
		() => import("@/registry/example/dropdown/dropdown-preview")
	),
	"dropdown-with-checkbox-example": React.lazy(
		() => import("@/registry/example/dropdown/dropdown-with-checkbox-example")
	),
	"dropdown-with-dropdown-checkbox": React.lazy(
		() => import("@/registry/example/dropdown/dropdown-with-dropdown-checkbox")
	),
	"dropdown-with-radio": React.lazy(
		() => import("@/registry/example/dropdown/dropdown-with-radio")
	),
	"user-profile-dropdown-example": React.lazy(
		() => import("@/registry/example/dropdown/user-profile-dropdown-example")
	),
	"empty-preview": React.lazy(
		() => import("@/registry/example/empty/empty-preview")
	),
	"no-comments-yet": React.lazy(
		() => import("@/registry/example/empty/no-comments-yet")
	),
	"no-files-uploaded": React.lazy(
		() => import("@/registry/example/empty/no-files-uploaded")
	),
	"no-internet-connection": React.lazy(
		() => import("@/registry/example/empty/no-internet-connection")
	),
	"no-messages": React.lazy(
		() => import("@/registry/example/empty/no-messages")
	),
	"no-notifications": React.lazy(
		() => import("@/registry/example/empty/no-notifications")
	),
	"no-projects-yet": React.lazy(
		() => import("@/registry/example/empty/no-projects-yet")
	),
	"no-recent-activity": React.lazy(
		() => import("@/registry/example/empty/no-recent-activity")
	),
	"no-reports-yet": React.lazy(
		() => import("@/registry/example/empty/no-reports-yet")
	),
	"no-search-results": React.lazy(
		() => import("@/registry/example/empty/no-search-results")
	),
	"no-such-directory": React.lazy(
		() => import("@/registry/example/empty/no-such-directory")
	),
	"unexpected-error": React.lazy(
		() => import("@/registry/example/empty/unexpected-error")
	),
	"document-file": React.lazy(
		() => import("@/registry/example/file-upload/document-file")
	),
	"document-upload": React.lazy(
		() => import("@/registry/example/file-upload/document-upload")
	),
	"file-upload-example": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-example")
	),
	"file-upload-preview": React.lazy(
		() => import("@/registry/example/file-upload/file-upload-preview")
	),
	"image-upload": React.lazy(
		() => import("@/registry/example/file-upload/image-upload")
	),
	"form-preview": React.lazy(
		() => import("@/registry/example/form/form-preview")
	),
	"sign-in-form": React.lazy(
		() => import("@/registry/example/form/sign-in-form")
	),
	"sign-up-form": React.lazy(
		() => import("@/registry/example/form/sign-up-form")
	),
	"hover-card-group-quick-view": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-group-quick-view")
	),
	"hover-card-influencer-profile": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-influencer-profile")
	),
	"hover-card-post-images-and-stats": React.lazy(
		() =>
			import("@/registry/example/hover-card/hover-card-post-images-and-stats")
	),
	"hover-card-preview": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-preview")
	),
	"hover-card-user-metrics": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-user-metrics")
	),
	"hover-card-user-mini-profile": React.lazy(
		() => import("@/registry/example/hover-card/hover-card-user-mini-profile")
	),
	"credit-card-input-preview": React.lazy(
		() => import("@/registry/example/input/credit-card-input-preview")
	),
	"disabled-input": React.lazy(
		() => import("@/registry/example/input/disabled-input")
	),
	"email-input-preview": React.lazy(
		() => import("@/registry/example/input/email-input-preview")
	),
	"input-clear-button": React.lazy(
		() => import("@/registry/example/input/input-clear-button")
	),
	"input-color": React.lazy(
		() => import("@/registry/example/input/input-color")
	),
	"input-form": React.lazy(() => import("@/registry/example/input/input-form")),
	"input-groups": React.lazy(
		() => import("@/registry/example/input/input-groups")
	),
	"input-preview": React.lazy(
		() => import("@/registry/example/input/input-preview")
	),
	"input-search-suggestions": React.lazy(
		() => import("@/registry/example/input/input-search-suggestions")
	),
	"input-search": React.lazy(
		() => import("@/registry/example/input/input-search")
	),
	"input-size": React.lazy(() => import("@/registry/example/input/input-size")),
	"input-wrapper": React.lazy(
		() => import("@/registry/example/input/input-wrapper")
	),
	"invalid-input": React.lazy(
		() => import("@/registry/example/input/invalid-input")
	),
	"number-input-preview": React.lazy(
		() => import("@/registry/example/input/number-input-preview")
	),
	"password-preview": React.lazy(
		() => import("@/registry/example/input/password-preview")
	),
	"password-toggle-on-focus": React.lazy(
		() => import("@/registry/example/input/password-toggle-on-focus")
	),
	"password-toggle-visible": React.lazy(
		() => import("@/registry/example/input/password-toggle-visible")
	),
	"password-validation-example": React.lazy(
		() => import("@/registry/example/input/password-validation-example")
	),
	"url-input-preview": React.lazy(
		() => import("@/registry/example/input/url-input-preview")
	),
	"label-preview": React.lazy(
		() => import("@/registry/example/label/label-preview")
	),
	"otp-field-auto-submit": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-auto-submit")
	),
	"otp-field-disabled": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-disabled")
	),
	"otp-field-form": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-form")
	),
	"otp-field-preview": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-preview")
	),
	"otp-field-type-password": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-type-password")
	),
	"otp-field-validation-type": React.lazy(
		() => import("@/registry/example/otp-field/otp-field-validation-type")
	),
	"otp-size": React.lazy(() => import("@/registry/example/otp-field/otp-size")),
	"pagination-card-example": React.lazy(
		() => import("@/registry/example/pagination/pagination-card-example")
	),
	"pagination-example-preview": React.lazy(
		() => import("@/registry/example/pagination/pagination-example-preview")
	),
	"pagination-text-example": React.lazy(
		() => import("@/registry/example/pagination/pagination-text-example")
	),
	"rows-per-page-example": React.lazy(
		() => import("@/registry/example/pagination/rows-per-page-example")
	),
	"exclude-countries-example": React.lazy(
		() =>
			import("@/registry/example/phone-number-input/exclude-countries-example")
	),
	"international-phone-hook-example": React.lazy(
		() =>
			import(
				"@/registry/example/phone-number-input/international-phone-hook-example"
			)
	),
	"national-phone-number-example": React.lazy(
		() =>
			import(
				"@/registry/example/phone-number-input/national-phone-number-example"
			)
	),
	"only-countries-phone": React.lazy(
		() => import("@/registry/example/phone-number-input/only-countries-phone")
	),
	"phone-number-example": React.lazy(
		() => import("@/registry/example/phone-number-input/phone-number-example")
	),
	"phone-number-no-formatting": React.lazy(
		() =>
			import("@/registry/example/phone-number-input/phone-number-no-formatting")
	),
	"phone-number-static": React.lazy(
		() => import("@/registry/example/phone-number-input/phone-number-static")
	),
	"preferred-countries-phone": React.lazy(
		() =>
			import("@/registry/example/phone-number-input/preferred-countries-phone")
	),
	"popover-align": React.lazy(
		() => import("@/registry/example/popover/popover-align")
	),
	"popover-emoji": React.lazy(
		() => import("@/registry/example/popover/popover-emoji")
	),
	"popover-emoji2": React.lazy(
		() => import("@/registry/example/popover/popover-emoji2")
	),
	"popover-preview": React.lazy(
		() => import("@/registry/example/popover/popover-preview")
	),
	"popover-side": React.lazy(
		() => import("@/registry/example/popover/popover-side")
	),
	"downloading-progress": React.lazy(
		() => import("@/registry/example/progress/downloading-progress")
	),
	"progress-example": React.lazy(
		() => import("@/registry/example/progress/progress-example")
	),
	"progress-preview": React.lazy(
		() => import("@/registry/example/progress/progress-preview")
	),
	"radio-group-disabled": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-disabled")
	),
	"radio-group-form": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-form")
	),
	"radio-group-preview": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-preview")
	),
	"radio-group-size": React.lazy(
		() => import("@/registry/example/radio-group/radio-group-size")
	),
	"handle-on-hover": React.lazy(
		() => import("@/registry/example/resizable/handle-on-hover")
	),
	"resizable-example": React.lazy(
		() => import("@/registry/example/resizable/resizable-example")
	),
	"resizable-preview": React.lazy(
		() => import("@/registry/example/resizable/resizable-preview")
	),
	"scroll-area-preview": React.lazy(
		() => import("@/registry/example/scroll-area/scroll-area-preview")
	),
	"select-custom-indicator": React.lazy(
		() => import("@/registry/example/select/select-custom-indicator")
	),
	"select-form": React.lazy(
		() => import("@/registry/example/select/select-form")
	),
	"select-indicator-position": React.lazy(
		() => import("@/registry/example/select/select-indicator-position")
	),
	"select-preview": React.lazy(
		() => import("@/registry/example/select/select-preview")
	),
	"select-sizes": React.lazy(
		() => import("@/registry/example/select/select-sizes")
	),
	"select-time-picker": React.lazy(
		() => import("@/registry/example/select/select-time-picker")
	),
	"select-with-avatar": React.lazy(
		() => import("@/registry/example/select/select-with-avatar")
	),
	"select-with-badge": React.lazy(
		() => import("@/registry/example/select/select-with-badge")
	),
	"skeleton-preview": React.lazy(
		() => import("@/registry/example/skeleton/skeleton-preview")
	),
	"price-range": React.lazy(
		() => import("@/registry/example/slider/price-range")
	),
	"range-slider": React.lazy(
		() => import("@/registry/example/slider/range-slider")
	),
	"slider-preview": React.lazy(
		() => import("@/registry/example/slider/slider-preview")
	),
	"slider-with-input": React.lazy(
		() => import("@/registry/example/slider/slider-with-input")
	),
	"slider-with-marks": React.lazy(
		() => import("@/registry/example/slider/slider-with-marks")
	),
	"slider-with-stepper": React.lazy(
		() => import("@/registry/example/slider/slider-with-stepper")
	),
	"slider-with-tooltip": React.lazy(
		() => import("@/registry/example/slider/slider-with-tooltip")
	),
	"sonner-expand": React.lazy(
		() => import("@/registry/example/sonner/sonner-expand")
	),
	"sonner-placement": React.lazy(
		() => import("@/registry/example/sonner/sonner-placement")
	),
	"sonner-position": React.lazy(
		() => import("@/registry/example/sonner/sonner-position")
	),
	"sonner-preview": React.lazy(
		() => import("@/registry/example/sonner/sonner-preview")
	),
	"sonner-variant": React.lazy(
		() => import("@/registry/example/sonner/sonner-variant")
	),
	"spinner-colors": React.lazy(
		() => import("@/registry/example/spinner/spinner-colors")
	),
	"spinner-preview": React.lazy(
		() => import("@/registry/example/spinner/spinner-preview")
	),
	"spinner-sizes": React.lazy(
		() => import("@/registry/example/spinner/spinner-sizes")
	),
	"icon-inside-switch": React.lazy(
		() => import("@/registry/example/switch/icon-inside-switch")
	),
	"square-switch": React.lazy(
		() => import("@/registry/example/switch/square-switch")
	),
	"switch-card": React.lazy(
		() => import("@/registry/example/switch/switch-card")
	),
	"switch-disabled": React.lazy(
		() => import("@/registry/example/switch/switch-disabled")
	),
	"switch-form": React.lazy(
		() => import("@/registry/example/switch/switch-form")
	),
	"switch-icon-indicator": React.lazy(
		() => import("@/registry/example/switch/switch-icon-indicator")
	),
	"switch-on-off": React.lazy(
		() => import("@/registry/example/switch/switch-on-off")
	),
	"switch-preview": React.lazy(
		() => import("@/registry/example/switch/switch-preview")
	),
	"switch-sizes": React.lazy(
		() => import("@/registry/example/switch/switch-sizes")
	),
	"text-switch": React.lazy(
		() => import("@/registry/example/switch/text-switch")
	),
	"basic-data-table": React.lazy(
		() => import("@/registry/example/table/basic-data-table")
	),
	"dragable-table": React.lazy(
		() => import("@/registry/example/table/dragable-table")
	),
	"expand-table": React.lazy(
		() => import("@/registry/example/table/expand-table")
	),
	"resize-table": React.lazy(
		() => import("@/registry/example/table/resize-table")
	),
	"table-example": React.lazy(
		() => import("@/registry/example/table/table-example")
	),
	"table-preview": React.lazy(
		() => import("@/registry/example/table/table-preview")
	),
	"tabs-disabled": React.lazy(
		() => import("@/registry/example/tabs/tabs-disabled")
	),
	"tabs-preview": React.lazy(
		() => import("@/registry/example/tabs/tabs-preview")
	),
	"tabs-size-large": React.lazy(
		() => import("@/registry/example/tabs/tabs-size-large")
	),
	"tabs-size-medium": React.lazy(
		() => import("@/registry/example/tabs/tabs-size-medium")
	),
	"tabs-size-small": React.lazy(
		() => import("@/registry/example/tabs/tabs-size-small")
	),
	"tabs-variant-ghost": React.lazy(
		() => import("@/registry/example/tabs/tabs-variant-ghost")
	),
	"tabs-variant-open": React.lazy(
		() => import("@/registry/example/tabs/tabs-variant-open")
	),
	"tabs-variant-outline-ghost": React.lazy(
		() => import("@/registry/example/tabs/tabs-variant-outline-ghost")
	),
	"tabs-variant-outline": React.lazy(
		() => import("@/registry/example/tabs/tabs-variant-outline")
	),
	"tabs-vertical": React.lazy(
		() => import("@/registry/example/tabs/tabs-vertical")
	),
	"tabs-width-full": React.lazy(
		() => import("@/registry/example/tabs/tabs-width-full")
	),
	"tabs-with-badge": React.lazy(
		() => import("@/registry/example/tabs/tabs-with-badge")
	),
	"tabs-with-icon": React.lazy(
		() => import("@/registry/example/tabs/tabs-with-icon")
	),
	"limited-characters": React.lazy(
		() => import("@/registry/example/text-area/limited-characters")
	),
	"text-area-disabled": React.lazy(
		() => import("@/registry/example/text-area/text-area-disabled")
	),
	"text-area-form": React.lazy(
		() => import("@/registry/example/text-area/text-area-form")
	),
	"text-area-preview": React.lazy(
		() => import("@/registry/example/text-area/text-area-preview")
	),
	"tooltip-align": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-align")
	),
	"tooltip-preview": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-preview")
	),
	"tooltip-side": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-side")
	),
	"tooltip-theme": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-theme")
	),
	"tooltip-with-arrow": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-arrow")
	),
	"tooltip-with-chart": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-chart")
	),
	"tooltip-with-icon-title": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-icon-title")
	),
	"tooltip-with-image": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-image")
	),
	"tooltip-with-title-description": React.lazy(
		() => import("@/registry/example/tooltip/tooltip-with-title-description")
	),
}

export default registry
