// This file is autogenerated by scripts/build-registry-map.ts
// Do not edit this file directly.
import * as React from "react"

export type ThemerPreviewEntry = {
	name: string
	component: React.LazyExoticComponent<React.ComponentType>
}

export const themerPreviewRegistry: Record<string, ThemerPreviewEntry> = {
	accordion: {
		name: "accordion-preview",
		component: React.lazy(
			() => import("@/registry/example/accordion/accordion-preview")
		),
	},
	alert: {
		name: "alert-preview",
		component: React.lazy(
			() => import("@/registry/example/alert/alert-preview")
		),
	},
	"alert-dialog": {
		name: "alert-dialog-preview",
		component: React.lazy(
			() => import("@/registry/example/alert-dialog/alert-dialog-preview")
		),
	},
	"aspect-ratio": {
		name: "aspect-ratio-preview-16-9",
		component: React.lazy(
			() => import("@/registry/example/aspect-ratio/aspect-ratio-preview-16-9")
		),
	},
	"auth-blocks": {
		name: "account-verified",
		component: React.lazy(
			() => import("@/registry/example/auth-blocks/account-verified")
		),
	},
	avatar: {
		name: "avatar-preview",
		component: React.lazy(
			() => import("@/registry/example/avatar/avatar-preview")
		),
	},
	badge: {
		name: "badge-example",
		component: React.lazy(
			() => import("@/registry/example/badge/badge-example")
		),
	},
	banner: {
		name: "banner-example-preview",
		component: React.lazy(
			() => import("@/registry/example/banner/banner-example-preview")
		),
	},
	breadcrumb: {
		name: "breadcrumb-preview",
		component: React.lazy(
			() => import("@/registry/example/breadcrumb/breadcrumb-preview")
		),
	},
	button: {
		name: "button-example-preview",
		component: React.lazy(
			() => import("@/registry/example/button/button-example-preview")
		),
	},
	calendar: {
		name: "calendar-preview",
		component: React.lazy(
			() => import("@/registry/example/calendar/calendar-preview")
		),
	},
	card: {
		name: "card-preview",
		component: React.lazy(() => import("@/registry/example/card/card-preview")),
	},
	carousel: {
		name: "carousel-preview",
		component: React.lazy(
			() => import("@/registry/example/carousel/carousel-preview")
		),
	},
	checkbox: {
		name: "checkbox-preview",
		component: React.lazy(
			() => import("@/registry/example/checkbox/checkbox-preview")
		),
	},
	"code-area": {
		name: "code-area-preview",
		component: React.lazy(
			() => import("@/registry/example/code-area/code-area-preview")
		),
	},
	collapsible: {
		name: "collapsible-preview",
		component: React.lazy(
			() => import("@/registry/example/collapsible/collapsible-preview")
		),
	},
	combobox: {
		name: "combobox-preview",
		component: React.lazy(
			() => import("@/registry/example/combobox/combobox-preview")
		),
	},
	command: {
		name: "command-preview",
		component: React.lazy(
			() => import("@/registry/example/command/command-preview")
		),
	},
	"currency-input": {
		name: "currency-input-example",
		component: React.lazy(
			() => import("@/registry/example/currency-input/currency-input-example")
		),
	},
	"date-picker": {
		name: "date-picker-preview",
		component: React.lazy(
			() => import("@/registry/example/date-picker/date-picker-preview")
		),
	},
	dialog: {
		name: "dialog-preview",
		component: React.lazy(
			() => import("@/registry/example/dialog/dialog-preview")
		),
	},
	divider: {
		name: "divider-preview",
		component: React.lazy(
			() => import("@/registry/example/divider/divider-preview")
		),
	},
	drawer: {
		name: "drawer-example-preview",
		component: React.lazy(
			() => import("@/registry/example/drawer/drawer-example-preview")
		),
	},
	dropdown: {
		name: "dropdown-preview",
		component: React.lazy(
			() => import("@/registry/example/dropdown/dropdown-preview")
		),
	},
	empty: {
		name: "empty-preview",
		component: React.lazy(
			() => import("@/registry/example/empty/empty-preview")
		),
	},
	"file-upload": {
		name: "file-upload-preview",
		component: React.lazy(
			() => import("@/registry/example/file-upload/file-upload-preview")
		),
	},
	form: {
		name: "form-preview",
		component: React.lazy(() => import("@/registry/example/form/form-preview")),
	},
	"hover-card": {
		name: "hover-card-preview",
		component: React.lazy(
			() => import("@/registry/example/hover-card/hover-card-preview")
		),
	},
	input: {
		name: "input-preview",
		component: React.lazy(
			() => import("@/registry/example/input/input-preview")
		),
	},
	label: {
		name: "label-preview",
		component: React.lazy(
			() => import("@/registry/example/label/label-preview")
		),
	},
	"otp-field": {
		name: "otp-field-preview",
		component: React.lazy(
			() => import("@/registry/example/otp-field/otp-field-preview")
		),
	},
	pagination: {
		name: "pagination-example-preview",
		component: React.lazy(
			() => import("@/registry/example/pagination/pagination-example-preview")
		),
	},
	"phone-number-input": {
		name: "exclude-countries-example",
		component: React.lazy(
			() =>
				import(
					"@/registry/example/phone-number-input/exclude-countries-example"
				)
		),
	},
	popover: {
		name: "popover-preview",
		component: React.lazy(
			() => import("@/registry/example/popover/popover-preview")
		),
	},
	progress: {
		name: "progress-preview",
		component: React.lazy(
			() => import("@/registry/example/progress/progress-preview")
		),
	},
	"radio-group": {
		name: "radio-group-preview",
		component: React.lazy(
			() => import("@/registry/example/radio-group/radio-group-preview")
		),
	},
	resizable: {
		name: "resizable-preview",
		component: React.lazy(
			() => import("@/registry/example/resizable/resizable-preview")
		),
	},
	"scroll-area": {
		name: "scroll-area-preview",
		component: React.lazy(
			() => import("@/registry/example/scroll-area/scroll-area-preview")
		),
	},
	select: {
		name: "select-preview",
		component: React.lazy(
			() => import("@/registry/example/select/select-preview")
		),
	},
	skeleton: {
		name: "skeleton-preview",
		component: React.lazy(
			() => import("@/registry/example/skeleton/skeleton-preview")
		),
	},
	slider: {
		name: "slider-preview",
		component: React.lazy(
			() => import("@/registry/example/slider/slider-preview")
		),
	},
	sonner: {
		name: "sonner-preview",
		component: React.lazy(
			() => import("@/registry/example/sonner/sonner-preview")
		),
	},
	spinner: {
		name: "spinner-preview",
		component: React.lazy(
			() => import("@/registry/example/spinner/spinner-preview")
		),
	},
	switch: {
		name: "switch-preview",
		component: React.lazy(
			() => import("@/registry/example/switch/switch-preview")
		),
	},
	table: {
		name: "table-preview",
		component: React.lazy(
			() => import("@/registry/example/table/table-preview")
		),
	},
	tabs: {
		name: "tabs-preview",
		component: React.lazy(() => import("@/registry/example/tabs/tabs-preview")),
	},
	"text-area": {
		name: "text-area-preview",
		component: React.lazy(
			() => import("@/registry/example/text-area/text-area-preview")
		),
	},
	tooltip: {
		name: "tooltip-preview",
		component: React.lazy(
			() => import("@/registry/example/tooltip/tooltip-preview")
		),
	},
}
